### ISSUE TITLE
🐛 [firebase_core] PlatformException(ExecutionException, Nonnull field "messagingSenderId" is null

### ISSUE THREAD

**Issue by MovingMelody** [firebase/flutterfire#10306]
## Bug report

**Describe the bug**
Using Firebase Messaging and Firestore for Flutter Module and after bundling module with kotlin android app this issue is happening.
Firebase is failing to Initialize. Is there any way to share the Firebase Instance created in kotlin app to Firebase Module ?

### Steps to reproduce

1. Integrate Firebase in Flutter Module.
2. Bundle the Flutter Module with Existing Native Android App
3. Launch the bundled Application and this issue is happening.

```
Failed to Initialize Firebase
2023-01-20 12:25:11.596 15460-15711 flutter                 com.nitara.farmer.qa                 I  PlatformException(ExecutionException, java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Nonnull field "messagingSenderId" is null., Cause: java.lang.IllegalStateException: Nonnull field "messagingSenderId" is null., Stacktrace: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Nonnull field "messagingSenderId" is null.
                                                                                                    	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.2:5)
                                                                                                    	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
                                                                                                    	at io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin.lambda$initializeCore$3$io-flutter-plugins-firebase-core-FlutterFirebaseCorePlugin(FlutterFirebaseCorePlugin.java:174)
                                                                                                    	at io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin$$ExternalSyntheticLambda1.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:63
```

**Comment by MovingMelody** [comment]
We are using Firebase in Native Kotlin app and recently we've developed one specific Module using flutter which uses Firebase too. So the above issue is happening while bundling Flutter Module with Kotlin Application. 

[FlutterFirebaseCorePlugin.java](https://github.com/firebase/flutterfire/blob/e0087c845c7526c11a4241a26d39d4673b0ad29d/packages/firebase_core/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java#L53) In this file Line no : 53 Firebase Core android package FirebaseOptions data class still expecting `gcmSenderId` which is deprecated in favor of `messagingSenderId`.


Temp Fix : 
I've hard-coded the messaging sender Id then it's working fine. 
```java
//    if (options.getGcmSenderId() != null) {
      firebaseOptions.setMessagingSenderId("hard_coded_sender_id");
//    }
```

@darshankawar

**Comment by darshankawar** [comment]
Thanks for the update and sharing details @MovingMelody 


> `gcmSenderId` which is deprecated in favor of `messagingSenderId`.

This has been already addressed in `firebase_core` plugin https://pub.dev/packages/firebase_core/changelog#050
And it shouldn't be the case using latest version of plugin. Can you provide the plugin versions you are using in your project ?

**Comment by MovingMelody** [comment]
Hi @darshankawar. Thanks for the quick response.

Plugin Versions
```
  # Firebase Suite - pubspec.yaml
  cloud_firestore: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.10
```
Can you check the file [FlutterFirebaseCorePlugin.java](https://github.com/firebase/flutterfire/blob/e0087c845c7526c11a4241a26d39d4673b0ad29d/packages/firebase_core/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java#L53)  It's still `gcmSenderId`

And that too it's happening only when the both Kotlin and Flutter modules are using Firebase

**Comment by darshankawar** [comment]
`gcmSenderId` seems to be coming from native Firebase's `FirebaseOptions` class:

https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseOptions#getGcmSenderId()

I'll keep this issue open for team's insights on expected behavior.

**Comment by Lyokone** [comment]
@MovingMelody What is the version of BOM you are using in your Native app?

**Comment by MovingMelody** [comment]
Hey @Lyokone. It's `31.2.0`
```
implementation platform('com.google.firebase:firebase-bom:31.2.0')
```

**Comment by Lyokone** [comment]
We have just upgraded to it https://github.com/firebase/flutterfire/pull/10369, should be fixed next release

**Comment by MovingMelody** [comment]
@Lyokone @darshankawar I've updated Android Firebase-bom version to `31.2.3`. This issue still persists

**Comment by MovingMelody** [comment]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/39739036/224962570-9ed06759-a94b-4e00-a983-fc6cc058531b.png)


We are bundling Flutter Module with Native Application and both applications are using Firebase to perform some data operations. And this issue is popping up as soon as user launches the flutter module

**Comment by Lyokone** [comment]
I'll keep this open for investigation then. Could you provide a complete repro example so I can investigate this?

**Comment by mytrancoinhako** [comment]
I also got this issue when integrate flutter inside android native with lastest version of bom firebase in android and firebase_core in flutter.

**Comment by LaxmikanthMadhyastha** [comment]
did anyone got workaround for this?

**Comment by Lyokone** [comment]
Didn't get any response for more than 1 year from the author about a complete reproduction sample. I'll close this. If anyone is experiencing the same issue, feel free to reopen.
