### ISSUE TITLE
🐛 [firebase_auth] [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store. 

### ISSUE THREAD

**Issue by dharambudh1** [firebase/flutterfire#10750]
I am getting an error while fetching the sms code from the verification completed callback. I am getting an SMS on the physical device, but it fails to get set in the text field.

Error: 
"E/FirebaseAuth(32222): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store."

![alt text](https://i.postimg.cc/Vs74K9kp/Screenshot-2023-04-09-at-12-38-37-PM.png "img")

In the screenshot, there's my authentication service class, which I've created, in that the code sent callback is working as expected, but the verification completed callback is never getting called.

Line no. 22 is never getting called.

Flutter Version:
Flutter (Channel stable, 3.7.0, on macOS 13.3 22E252 darwin-arm64, locale en-IN)

Plugin Version:
firebase_app_check: ^0.1.2
firebase_auth: ^4.4.0
firebase_core: ^2.9.0

Important:

I've set up Firebase "Phone Authentication" in Firebase Console & App
I've set up Firebase "App Check" in Firebase Console & App
I've set up SHA Keys (Debug & Release) in Firebase Console

**Comment by DimaLiubko** [comment]
I faced the same issue 
<img width="1485" alt="auth_service dart" src="https://user-images.githubusercontent.com/29432498/230866176-70f0fea5-feec-491e-b0f8-4e2296db7b25.png">

**Comment by darshankawar** [comment]
@dharambudh1 
Can you take a look at [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and see if using it, you get same error or not ?

**Comment by dharambudh1** [comment]
@darshankawar, Yes, I just went through the official example, I've checked their source code & I didn't find any resolution there. 

https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/auth.dart#L490

Look at Line no. 490. That callback is empty.

**Comment by ridwan-aswan** [comment]
Please help me, I'm experiencing a similar issue. I have tried several approaches:

1. Adding SHA-1 and SHA-256 (Debug, Release, and Key from Play Console) in the Firebase project settings.
2. Adding SHA-256 (Debug, Release, and Key from Play Console) in App Check (Play Integrity).
3. Connecting to Google Cloud Console in Play Console App Integrity.
4. Using Authentication SDK v21.2.0+ (Firebase BoM v31.4.0+) as per the documentation at [https://firebase.google.com/docs/auth/android/phone-auth](url)

I have spent a lot of time on this issue, and any help would be greatly appreciated.

**Comment by darshankawar** [comment]
Thanks for the feedback. Keeping the issue open for team's thoughts on the reported behavior.

/cc @Lyokone

**Comment by Lyokone** [comment]
Hello @dharambudh1,
Looking at your code, you are not using the callbacks correctly. Please look at the official example on how to use this function (the callback is meant to see if the verification has been successfully completed, but is not meant to get the credentials):
```
 await auth.verifyPhoneNumber(
          phoneNumber: phoneController.text,
          verificationCompleted: (_) {},
          verificationFailed: (e) {
            setState(() {
              error = '${e.message}';
            });
          },
          codeSent: (String verificationId, int? resendToken) async {
            final smsCode = await getSmsCodeFromUser(context);

            if (smsCode != null) {
              // Create a PhoneAuthCredential with the code
              final credential = PhoneAuthProvider.credential(
                verificationId: verificationId,
                smsCode: smsCode,
              );

              try {
                // Sign the user in (or link) with the credential
                await auth.signInWithCredential(credential);
              } on FirebaseAuthException catch (e) {
                setState(() {
                  error = e.message ?? '';
                });
              }
            }
          },
          codeAutoRetrievalTimeout: (e) {
            setState(() {
              error = e;
            });
          },
        );
```

For the 18002 error, did you publish the app on the Play Store already?

@ridwan-aswan 
I see that you are mentioning using `Using Authentication SDK v21.2.0+`, you are following the Android instructions and not the [Flutter ones](https://firebase.google.com/docs/auth/flutter/phone-auth). You should not add BOM manually.

**Comment by dharambudh1** [comment]
> verificationCompleted

I am pretty sure my method is correct because it was working a few weeks ago & I haven't changed anything from there. Verification completed callback is listening for the SMS (we can print SMS Code in the console using "credential.smsCode"). And if we want to perform autofill SMS (without using any 3rd party packages) at that time, that verification completion callback plays a most integral part. 

For example, "textEditingController.text = credential.smsCode".

BTW, we haven't published our app yet. It is still under development.

**Comment by ericmand** [comment]
I'm having same issue with an app that has been published to the app store. Was working before and now it isn't. @dharambudh1 did you figure out a fix?

**Comment by Lyokone** [comment]
We published a new version of [firebase_core](https://pub.dev/packages/firebase_core) that includes some fixes on the Native SDK. Can you try to see if bumping your app to the latest firebase_core and firebase_auth package version solve the issue (don't hesitate to run `flutterfire update` to ensure that you are using the latest packages)

**Comment by ericmand** [comment]
That fixed it for me!

**Comment by dharambudh1** [comment]
> We published a new version of [firebase_core](https://pub.dev/packages/firebase_core) that includes some fixes on the Native SDK. Can you try to see if bumping your app to the latest firebase_core and firebase_auth package version solve the issue (don't hesitate to run `flutterfire update` to ensure that you are using the latest packages)

I'm still getting below-mentioned error:
![alt text](https://i.postimg.cc/kgjcmkxP/Screenshot-2023-04-22-at-12-09-15-PM-cleanup.png "img")

**Comment by GrandeSamarone** [comment]
Guys, to test the app, do you have to put it on the play store?
mine worked normally now it's giving the same problem

**Comment by elenacrst** [comment]
I'm getting the same error in logs
```
SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store.
```

I did all of the following
1. setup App Integrity in Google Play Console and linked the correct project number from Google Cloud [same as the Firebase project]
2. added this dependency to android/app/build.gradle : ```implementation 'com.google.android.play:integrity:1.1.0'```
3. I have my SHA-1 and SHA-256 correctly added to Firebase console.
4. I updated the dependencies in `pubspec.yaml` to `firebase_core: ^2.13.0` and `firebase_auth: ^4.6.1`. 

Is there anything else I might be missing? 

The app would always open recaptcha for real phone numbers now. For the phone numbers added as test phones in Firebase console, recaptcha is skipped.

**Comment by ThakarRajesh** [comment]
Hello,
We're encountering a same problem, and we're actively searching for a solution. if any one sound solution please let me know.

**Comment by priteshkumbhare** [comment]
Is it possible to work it out without necessarily publishing it on Play Store?
I have done all the steps in Firebase(SHA keys, google-services.json, Play Integrity in App Check), flutter(updating firebase_core, firebase_auth) and build.grade in android/app(firebase-auth-ktx, firebase-auth, firebase-bom, firebase-app check-play integrity, firebase-appcheck-ktx) but no success.
After all this, reCaptcha screen is skipped only for test phone numbers. I suspect publishing to Play Store would be mandatory but I am not very sure.

**Comment by russellwheatley** [comment]
It is required to publish your app in the play store for the play integrity provider to work. You can use the internal testing track to test it works before publishing to users. You're likely getting the app signing key from the Play Store which needs inputting into your Firebase console.

**Comment by AK47-23** [comment]
https://firebase.google.com/docs/app-check/flutter/default-providers#initialize

Add app check package and give webProvider in main

**Comment by russellwheatley** [comment]
@dharambudh1 - did you manage to resolve this issue? [As mentioned previously](https://github.com/firebase/flutterfire/issues/10750#issuecomment-1761261731), you have to publish to Playstore for play integrity provider to work.

**Comment by priteshkumbhare** [comment]
One update, I have published the WinzTrade app on the Play Store in India. The reCaptcha is automatically removed when the app is downloaded from the Play Store.
