### ISSUE TITLE
🐛 [firebase_auth] SMS Verification Code Request Failed with Unknown Status Code after Firebase Upgrade

### ISSUE THREAD

**Issue by belh-sara** [firebase/flutterfire#10777]
## Bug report
After upgrading the Firebase packages version from the previous version to the new version, when trying to log in using Firebase on Android, I encounter the error message "SMS verification code request failed: unknown status code: 17499 Internal error encountered" in the console. Additionally, I see the error message "firebase exception: code unknown message null" in the console. However, with the test number, logging in works perfectly on both Android and iOS. I am using Flutter version 3.7.10 and Dart version 2.9.16. The Firebase packages affected by the upgrade include firebase_auth, firebase_messaging, firebase_dynamic_links, firebase_database, and firebase_crashlytics. As a result, I am unable to log in using Firebase with my own number on Android, but it works fine on iOS.

Package                          |     Old Version    |     New Version
firebase_core                  |        2.3.0            |        ^2.9.0
firebase_analytics           |        10.0.6          |        ^10.2.0
firebase_auth                  |        4.1.4            |        ^4.2.2
firebase_messaging        |        14.1.2          |       ^14.4.0
firebase_dynamic_links   |        5.0.6            |       ^5.1.0
firebase_database           |       10.0.6           |       ^10.1.0
firebase_app_check        |        0.1.1+5        |       ^0.1.2
firebase_crashlytics         |        3.0               |       ^3.1.0

**Comment by darshankawar** [comment]
@belh-sara 
Can you provide both complete error logs ?
Can you also confirm if you have SHA1 and SHA256 keys aren't corrupted and are proper ?
Have you enabled device check api in console ?

Moreover, is your firebase integrated using dart initialization or manually ? https://firebase.google.com/docs/flutter/setup?platform=android

**Comment by belh-sara** [comment]
here's  the complete error logs for the issue:
```
[+16811 ms] I/zzh     (14720): ForceRecaptchaFlow from phoneAuthOptions = false, ForceRecaptchaFlow from firebaseSettings = false
[   +1 ms] I/PlayCore(14720): UID: [10168]  PID: [14720] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=Y3QLk-c_QfY9wAMQdzMIyqvQS_tICnFB_cGzkVWL3-c, cloudProjectNumber=551503664846})
[        ] I/PlayCore(14720): UID: [10168]  PID: [14720] IntegrityService : Initiate binding to the service.
[  +15 ms] I/PlayCore(14720): UID: [10168]  PID: [14720] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.integrityservice.IntegrityService})
[   +1 ms] I/PlayCore(14720): UID: [10168]  PID: [14720] IntegrityService : linkToDeath
[+1485 ms] I/PlayCore(14720): UID: [10168]  PID: [14720] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
[        ] I/PlayCore(14720): UID: [10168]  PID: [14720] IntegrityService : Unbind from service.
[   +4 ms] W/System  (14720): Ignoring header X-Firebase-Locale because its value was null.
[ +409 ms] E/FirebaseAuth(14720): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 Internal error encountered.
[   +2 ms] D/FirebaseAuth(14720): Invoking original failure callbacks after phone verification failure for +213[my_number], error - An internal error has occurred. [ Internal error encountered. ]
[   +3 ms] I/flutter (14720): firebase exception: code unknown message null

```
I also checked and confirmed that my SHA1 and SHA256 are not corrupted, and the device check API is enabled in the console. However,when I discovered that the issue was with the version of the Firebase packages I was using. After some troubleshooting, I downgraded the Firebase packages version and the authentication started working again.

**Comment by voipworld** [comment]
i have same issue..., any solution?

**Comment by cardiffinc** [comment]
Facing the same issue. 

###using flutter. 
> firebase_auth: ^4.2.2

### Dev Details: 

> [√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.22621.1555], locale en-IN)
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.16)
> [!] Android Studio (version 2022.1)
> [√] VS Code (version 1.77.3)

### Error Details: 

```
I/zzh     ( 9857): ForceRecaptchaFlow from phoneAuthOptions = false, ForceRecaptchaFlow from firebaseSettings = false
W/System  ( 9857): Ignoring header X-Firebase-Locale because its value was null.
I/PlayCore( 9857): UID: [10238]  PID: [9857] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=[token], cloudProjectNumber=[num]})
I/PlayCore( 9857): UID: [10238]  PID: [9857] IntegrityService : Initiate binding to the service.
I/PlayCore( 9857): UID: [10238]  PID: [9857] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.integrityservice.IntegrityService})
I/PlayCore( 9857): UID: [10238]  PID: [9857] IntegrityService : linkToDeath
I/PlayCore( 9857): UID: [10238]  PID: [9857] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
W/FirebaseAuth( 9857): [FirebaseAuthFallback:] App hash will not be appended to the request.
W/FirebaseAuth( 9857): [SmsRetrieverHelper] Timeout of 0 specified; SmsRetriever will not start.
W/System  ( 9857): Ignoring header X-Firebase-Locale because its value was null.
I/PlayCore( 9857): UID: [10238]  PID: [9857] IntegrityService : Unbind from service.
E/FirebaseAuth( 9857): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 Internal error encountered.
D/FirebaseAuth( 9857): Invoking original failure callbacks after phone verification failure for +91 [MOBILE_NUM], error - An internal error has occurred. [ Internal error encountered. ]
```

**Comment by PVerniolle** [comment]
Some test:

Working fine with this conf :

  cloud_firestore: 4.4.5
  cloud_functions: 4.0.13
  firebase_analytics: 10.1.6
  firebase_app_check: 0.1.1+14
  firebase_auth: 4.3.0
  firebase_storage: 11.0.16
  firebase_core: 2.8.0
  firebase_crashlytics: 3.0.17
  firebase_dynamic_links: 5.0.17
  firebase_messaging: 14.3.0
  firebase_performance: 0.9.0+16
  firebase_remote_config: 3.0.15

Updating only firebase_core from 2.8.0 to 2.9.0 throw same issue.

**Comment by belh-sara** [comment]
@PVerniolle Thank you for your suggestion! I updated the Firebase version to the one you suggested, and it worked for me too. It seems like the problem was with the latest version of Firebase. Thanks again for your help!

**Comment by darshankawar** [comment]
I tried to replicate using [plugin example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) running on Android with latest versions and was able to sign in properly without any issues:

`User(displayName: null, email: dantesttest74@gmail.com, emailVerified: true, isAnonymous: false, metadata: UserMetadata(creationTime: 2023-02-08 10:06:58.051Z, lastSignInTime: 2023-04-13 10:57:53.098Z), phoneNumber: null, photoURL: null, providerData, [UserInfo(displayName: null, email: dantesttest74@gmail.com, phoneNumber: null, photoURL: null, providerId: password, uid: dantesttest74@gmail.com)], refreshToken: , tenantId: null, uid: YoaNWphb46ZRW4OlIgCTJTQ0Btz1)
`



> cloud_firestore: 4.4.5
> cloud_functions: 4.0.13
> firebase_analytics: 10.1.6
> firebase_app_check: 0.1.1+14
> firebase_auth: 4.3.0
> firebase_storage: 11.0.16
> firebase_core: 2.8.0
> firebase_crashlytics: 3.0.17
> firebase_dynamic_links: 5.0.17
> firebase_messaging: 14.3.0
> firebase_performance: 0.9.0+16
> firebase_remote_config: 3.0.15

This uses specific version of the plugins as they don't seem to have the caret (^).

I'll keep this issue open and label for team's attention.

/cc @Lyokone

**Comment by belh-sara** [comment]
Hello @darshankawar, I just wanted to clarify that the issue I'm facing is specifically with firebase_core version 2.9. I did try the suggested version that @PVerniolle provided, and it worked perfectly fine. However, when I upgraded to firebase_core version 2.9, the issue arose once again. Thank you for your help.

For reference, here are the packages versions that I am facing the issue with:

```
firebase_core ^2.9.0
firebase_analytics ^10.2.0
firebase_auth ^4.2.2
firebase_messaging ^14.4.0
firebase_dynamic_links ^5.1.0
firebase_database ^10.1.0
firebase_app_check ^0.1.2
firebase_crashlytics ^3.1.0
```

Here are the package versions that worked for me, suggested by @PVerniolle:
```
  firebase_core: 2.8.0
  firebase_analytics: 10.1.6
  firebase_auth: 4.3.0
  firebase_messaging: 14.3.0
  firebase_dynamic_links: 5.0.17
  firebase_database: 10.0.16
  firebase_app_check: 0.1.1+14
  firebase_crashlytics: 3.0.17
```

**Comment by SametSahin10** [comment]
I have the same issue.

**Comment by SametSahin10** [comment]
I've tried to use an older version of firebase_core and firebase_auth. It still does not work for me.

```
firebase_auth: 4.3.0
firebase_core: 2.8.0
```

**Comment by Lyokone** [comment]
Hello,

Can you try to update to the latest flutterfire_cli version, and run `flutterfire configure` again?

**Comment by SametSahin10** [comment]
> Hello,
> 
> Can you try to update to the latest flutterfire_cli version, and run `flutterfire configure` again?

I've tried. It's the same issue.

**Comment by yamauchieduardo** [comment]
Likewise, my production apps with a significant number of users now have SMS login disabled for Android. This is a high-priority (P0/P1) issue. @Lyokone @darshankawar

**Comment by Lyokone** [comment]
Latest version of Firebase core supports Play Integrity: https://firebase.google.com/support/release-notes/android#auth_v21-2-0, an upgrade to FlutterFire to AppCheck is in progress (using the latest [Native SDK](https://firebase.google.com/support/release-notes/android#auth_v21-3-0)).

Which verification provider are you using?

**Comment by yamauchieduardo** [comment]
I'm using the latest version of the Firebase core for Android and IOS version.
For Android I changed to Play Integrity.
I'm reverting all FlutterFire plugins update, I guess the actual versions are not ready for production.

**Comment by belh-sara** [comment]
@Lyokone 
> Latest version of Firebase core supports Play Integrity: https://firebase.google.com/support/release-notes/android#auth_v21-2-0, an upgrade to FlutterFire to AppCheck is in progress (using the latest [Native SDK](https://firebase.google.com/support/release-notes/android#auth_v21-3-0)).
> 
> Which verification provider are you using?
Hello,
 I'm currently using phone authentication as my verification provider

**Comment by iabdousd** [comment]
I am facing the same problem on Android using `firebase_auth` `4.4.0` and `flutter` `3.7.11`.

The problem is happening on production and on debug mode (with actual phone numbers and not test numbers).

**Comment by iabdousd** [comment]
> I'm using the latest version of the Firebase core for Android and IOS version.
> For Android I changed to Play Integrity.
> I'm reverted all FlutterFire plugins update, I guess the actual versions are not ready for production.

Could you please share the working versions for you?

**Comment by dreamfunlabs** [comment]
> Some test:
> 
> Working fine with this conf :
> 
> cloud_firestore: 4.4.5 cloud_functions: 4.0.13 firebase_analytics: 10.1.6 firebase_app_check: 0.1.1+14 firebase_auth: 4.3.0 firebase_storage: 11.0.16 firebase_core: 2.8.0 firebase_crashlytics: 3.0.17 firebase_dynamic_links: 5.0.17 firebase_messaging: 14.3.0 firebase_performance: 0.9.0+16 firebase_remote_config: 3.0.15
> 
> Updating only firebase_core from 2.8.0 to 2.9.0 throw same issue.

I thought I was losing it. Can confirm these work and rolling back.

**Comment by SametSahin10** [comment]
> > Some test:
> > Working fine with this conf :
> > cloud_firestore: 4.4.5 cloud_functions: 4.0.13 firebase_analytics: 10.1.6 firebase_app_check: 0.1.1+14 firebase_auth: 4.3.0 firebase_storage: 11.0.16 firebase_core: 2.8.0 firebase_crashlytics: 3.0.17 firebase_dynamic_links: 5.0.17 firebase_messaging: 14.3.0 firebase_performance: 0.9.0+16 firebase_remote_config: 3.0.15
> > Updating only firebase_core from 2.8.0 to 2.9.0 throw same issue.
> 
> I thought I was losing it. Can confirm these work and rolling back.

I've switched to these versions on firebase packages but I'm still having the issue. It's interesting.

**Comment by yamauchieduardo** [comment]
A reverted to:

```
  cloud_firestore: 4.5.1
  cloud_functions: 4.1.0
  firebase_analytics: 10.2.0
  firebase_app_check: 0.1.2+1
  firebase_auth: 4.4.1
  firebase_core: 2.9.0
  firebase_crashlytics: 3.1.0
  firebase_messaging: 14.4.0
  firebase_performance: 0.9.1
```

**Comment by yamauchieduardo** [comment]
I reverted to:

```
  cloud_firestore: 4.4.3
  cloud_functions: 4.0.11
  firebase_analytics: 10.1.4
  firebase_app_check: 0.1.1+12
  firebase_auth: 4.2.9
  firebase_core: 2.7.0
  firebase_crashlytics: 3.0.15
  firebase_messaging: 14.2.5
  firebase_performance: 0.9.0+14
  firebase_storage: 11.0.14
```

**Comment by SametSahin10** [comment]
> I reverted to:
> 
> ```
>   cloud_firestore: 4.4.3
>   cloud_functions: 4.0.11
>   firebase_analytics: 10.1.4
>   firebase_app_check: 0.1.1+12
>   firebase_auth: 4.2.9
>   firebase_core: 2.7.0
>   firebase_crashlytics: 3.0.15
>   firebase_messaging: 14.2.5
>   firebase_performance: 0.9.0+14
>   firebase_storage: 11.0.14
> ```

With these, I've been able to receive the OTP once. Then, the issue started occurring again.

**Comment by SametSahin10** [comment]
> @SametSahin10, have you tried cleaning your files with 'flutter clean'? If you are using iOS, I recommend running 'pod repo update' and 'pod install' in the iOS folder.
> 
> Note: If you require a specific version, avoid using the "^" symbol in your pubspec.yaml file.

Yes. I've run `flutter clean`. Then `flutter pub get`. It's the same issue. I'm testing on Android.

**Comment by markglibres** [comment]
same issue here.. sms verification failed after upgrade...   firebase auth returns "unknown" error, but then after reverting to the old version firebase auth says that my number was blocked due to many attempts (though we've only tried to login once). I'm using Flutter 3.7.11... but it worked fine after setting my package versions as stated by @PVerniolle

**Comment by flysolution-hub** [comment]
Hi, i have same issue with firebase_core 2.9.0.
With firebase_core 2.8.0 it works but it uses safetynet for phone authentication.
I need firebase_core 2.9.0 to migrate to play integrity.
Did anyone fixed it?

**Comment by belh-sara** [comment]
Good morning! I wanted to share an update on the issue I was having. After some research, I found that the problem was related to Play Integrity. Specifically, I realized that my old code in android/app/build.gradle contained the following:

```
implementation 'com.google.android.play:integrity:1.1.0'
implementation 'com.google.android.gms:play-services-safetynet:18.0.1'
```
To fix the issue, I replaced this code with the following:

```

implementation platform('com.google.firebase:firebase-bom:31.5.0')
implementation 'com.google.firebase:firebase-appcheck-playintegrity'

```
This solved my initial problem, but I've encountered a new issue where the reCaptcha page still pops up even though I have configured Play Integrity. I'm currently investigating this issue and will update you if I find a solution. If you have any insights or suggestions, please let me know!

**Comment by belh-sara** [comment]
Hello again! I removed my previous message because I discovered that the latest version of Firebase Auth has solved my issue. I'm now using the following package versions:
firebase_core: ^2.9.0
firebase_analytics: ^10.2.0
firebase_auth: ^4.4.1
firebase_messaging: ^14.4.0
firebase_dynamic_links: ^5.1.0
firebase_database: ^10.1.0
firebase_app_check: ^0.1.2+1
firebase_crashlytics: ^3.1.0

Thank you for your help!

**Comment by kakky0418** [comment]
I checked the operation with the same version.
```
firebase_core: ^2.9.0
firebase_analytics: ^10.2.0
firebase_auth: ^4.4.1
firebase_messaging: ^14.4.0
firebase_dynamic_links: ^5.1.0
firebase_database: ^10.1.0
firebase_app_check: ^0.1.2+1
firebase_crashlytics: ^3.1.0
```

but there is a problem.
```
PlayCore: UID: [10584] PID: [1641] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=xxxxxxxxxxxxxxxxxx, cloudProjectNumber=xxxxxxxxxxxxxxxxxxxxxxxxxx})
PlayCore: UID: [10584] PID: [1641] IntegrityService : Initiate binding to the service.
PlayCore: UID: [10584] PID: [1641] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com. google.android.finsky.integrityservice.IntegrityService})
PlayCore: UID: [10584] PID: [1641] IntegrityService : linkToDeath
Finsky : [265] jxl.b(23): requestIntegrityToken() finished for [package_name]
PlayCore: UID: [10578] PID: [13639] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
PlayCore: UID: [10578] PID: [13639] IntegrityService : Unbind from service.
````

I am installing from an actual device, Google PlayStore.
Is anyone else experiencing the same problem?

**Comment by SametSahin10** [comment]
> I checked the operation with the same version.
> 
> > Hello again! I removed my previous message because I discovered that the latest version of Firebase Auth has solved my issue. I'm now using the following package versions:
> > ```
> > firebase_core: ^2.9.0
> > firebase_analytics: ^10.2.0
> > firebase_auth: ^4.4.1
> > firebase_messaging: ^14.4.0
> > firebase_dynamic_links: ^5.1.0
> > firebase_database: ^10.1.0
> > firebase_app_check: ^0.1.2+1
> > firebase_crashlytics: ^3.1.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you for your help!
> 
> but there is a problem.
> 
> ```
> PlayCore: UID: [10584] PID: [1641] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=xxxxxxxxxxxxxxxxxx, cloudProjectNumber=xxxxxxxxxxxxxxxxxxxxxxxxxx})
> PlayCore: UID: [10584] PID: [1641] IntegrityService : Initiate binding to the service.
> PlayCore: UID: [10584] PID: [1641] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com. google.android.finsky.integrityservice.IntegrityService})
> PlayCore: UID: [10584] PID: [1641] IntegrityService : linkToDeath
> Finsky : [265] jxl.b(23): requestIntegrityToken() finished for [package_name]
> PlayCore: UID: [10578] PID: [13639] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
> PlayCore: UID: [10578] PID: [13639] IntegrityService : Unbind from service.
> ```
> 
> I am installing from an actual device, Google PlayStore. Is anyone else experiencing the same problem?

I was getting the same IntegrityService logs. The issue of not being able receive OTP SMSs has been solved without making a single change on my case.

**Comment by iqram0004** [comment]
Hi,

Is anyone still facing this issue? I have tried with all latest packages of firebase, still same issue i'm getting. It was working perfectly before updating packages. Every time in SMS verification code, browser pops up with Recaptha with these logs mentioned in issue thread.

**Comment by hermitdemschoenenleben** [comment]
Yes, I'm still facing the same issue as well

**Comment by iqram0004** [comment]
> Hello again! I removed my previous message because I discovered that the latest version of Firebase Auth has solved my issue. I'm now using the following package versions:
> 
> ```
> firebase_core: ^2.9.0
> firebase_analytics: ^10.2.0
> firebase_auth: ^4.4.1
> firebase_messaging: ^14.4.0
> firebase_dynamic_links: ^5.1.0
> firebase_database: ^10.1.0
> firebase_app_check: ^0.1.2+1
> firebase_crashlytics: ^3.1.0
> ```
> 
> Thank you for your help!

Hi, can you please tell us how you fixed this issue. I agree it works with old package versions of firebase , but soon they will be deprecated or won't work with new android or other package updates. So we have to use new versions. Can we please not close any issue before having proper solution, if there is any proper solution can anyone please share?

**Comment by hermitdemschoenenleben** [comment]
after hours of trying various things, I think I fixed the problem now (or it was resolved spontaneously, who knows…)

I did two things that may have fixed the issue:
- In Play Store Developer Console -> App integrity, I removed a test that I created for debugging
- At the same page -> "Device Integrity" I selected the checkboxes "MEETS_BASIC_INTEGRITY" and "MEETS_STRONG_INTEGRITY"
