### ISSUE TITLE
Windows app doesn't build after updating to latest version of firebase_core

### ISSUE THREAD

**Issue by abdulrehmananwar** [firebase/flutterfire#10992]
yesterday after update to latest version of 
firebase_core: ^2.13.0
firebase_messaging: ^14.6.1

when i run my windows desktop it not running up

first it use my 6 Gb drive space .so i run flutter clean to clear my drive space and countinue to use

also return following error

```
Nuget.exe not found, trying to download or use cached version.
Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Creating directories for 'nuget-populate'
  Building Custom Rule C:/Users/Administrator/StudioProjects/tagerp/build/windows/_deps/nuget-subbuild/CMakeLists.txt
  Performing download step (download and verify) for 'nuget-populate'
  -- Downloading...
     dst='C:/Users/Administrator/StudioProjects/tagerp/build/windows/_deps/nuget-subbuild/nuget-populate-prefix/src/nuget.exe'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://dist.nuget.org/win-x86-commandline/v6.0.0/nuget.exe'
  CMake Error at nuget-subbuild/nuget-populate-prefix/src/nuget-populate-stamp/download-nuget-populate.cmake:170 (message):
    Each download failed!

CUSTOMBUILD : error : downloading 'https://dist.nuget.org/win-x86-commandline/v6.0.0/nuget.exe' failed [C:\Users\Administrator\StudioProjects\tagerp\build\windows\_deps\nuget-subbuild\nuget-populate.vcxproj]
            status_code: 28
            status_string: "Timeout was reached"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 152.199.23.209:443...

    Connected to dist.nuget.org (152.199.23.209) port 443 (#0)

    schannel: disabled automatic use of client certificate

    schannel: ALPN, offering h2

    schannel: ALPN, offering http/1.1

    SSL/TLS connection timeout

    Closing connection 0



            --- LOG END ---
```

**Comment by danagbemava-nc** [comment]
Hi @abdulrehmananwar, can you try the solutions in  https://github.com/Baseflow/flutter-permission-handler/issues/819#issuecomment-1145865674 or https://stackoverflow.com/questions/71734042/flutter-windows-build-nuget-is-not-installed to see if you're able to solve your issue? This can come up for any number of reasons and does not seem related to firebase_core. 

Please also make sure that your network connection is stable enough

**Comment by abdulrehmananwar** [comment]
network connection is stable
nuget.exe  also install and not returning error

after around 10 minitues it return following error
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
cmake -E tar: error: ZIP decompression failed (-5)
CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:71 (add_subdirectory):
  The source directory

    C:/Users/Administrator/StudioProjects/tagerp/build/windows/extracted/firebase_cpp_sdk

  does not contain a CMakeLists.txt file.


Exception: Unable to generate build files

**Comment by abdulrehmananwar** [comment]
its happed only when i add these packages if i remove these packaged application run smoothly
firebase_core: ^2.13.0
firebase_messaging: ^14.6.1

**Comment by Mikkelet** [comment]
Same problem here

**Comment by Ghali01** [comment]
did you find any solution?

**Comment by radomir9720** [comment]
I'm also having troubles with firebase_core >2.10.0.

Build fails with the following output:

<details> 
  <summary>Build output</summary>

```
Launching lib/main_development.dart on Windows in debug mode...
main_development.dart:1
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
196
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
7
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
2
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
1365
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
15
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
2
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
cmake -E tar: warning: unknown warning
438
cmake -E tar: warning: unknown warning
CMake Error: Problem with archive_write_finish_entry(): File size could not be restored
CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:25 (file):
  file failed to extract:
  C:/StudioProjects/pixel_app_flutter/build/windows/firebase_cpp_sdk_10.5.0.zip
2

Exception: Unable to generate build files
Exited (sigterm)
```

</details>

Initially, i had version 2.13.0 of firebase_core. I was getting the error above, then i opened the changelog of firebase_core, and saw changes in 2.11.0, that may be related to this error, so i tried to downgrade to 2.10.0, and it worked. On 2.11.0 i get the same error. So, in my case, changes in 2.11.0 is the reason.

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.19044.2846], locale ru-RU)
    • Flutter version 3.10.2 on channel stable at C:\development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (3 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.5.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\radom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2846]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.63

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi all, can anyone facing this issue please provide a complete minimal reproducible code sample so that we can investigate this? 

Thank you

**Comment by Ghali01** [comment]
> Hi all, can anyone facing this issue please provide a complete minimal reproducible code sample so that we can investigate this? 
> 
> Thank you

Hello it is compile error not runtime error 
In the first place firebase doesn't support windows  
It's just when we add firebase_core to `pubspec.yaml`  we can't build exe file

**Comment by radomir9720** [comment]
Hi @danagbemava-nc. In my case, i figured out that the build failed because of #10496. Then i took a look at Visual Studio Build Tools, installed on my machine (i have not installed all the default build tools, because of limited space on my disk with Windows), and assumed that this could be due to the fact that I have not installed required for #10496 build tool.

I installed C++/CLI support build tool, and issue gone.

**Comment by danagbemava-nc** [comment]
I can reproduce the issue using a new project. 

### Steps to reproduce
- run `flutter create foo`
- run `flutter pub add firebase_core`
- run `flutter build windows`


<details>
<summary> logs</summary>

```
Building with sound null safety

firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_filesystem_desktop_windows.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant_util.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_util.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_scheduler.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_base64.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_controller_desktop.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_callback.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_date_provider.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_filesystem_desktop_windows.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant_util.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_util.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_scheduler.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_base64.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_controller_desktop.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_callback.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_date_provider.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant_util.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_date_provider.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_controller_desktop.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2001: unresolved external symbol __imp__calloc_dbg [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "struct f_b_flatbuffers::StructDef * * __cdecl __std_find_trivial<struct f_b_flatbuffers::StructDef *,unsigned __int64>(struct f_b_flatbuffers::StructDef * *,struct f_b_flatbuffers::StructDef * *,unsigned __int64)" (??$__std_find_trivial@PEAUStructDef@f_b_flatbuffers@@_K@@YAPEAPEAUStructDef@f_b_flatbuffers@@PEAPEAU01@0_K@Z) [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8 [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z) [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void * __cdecl std::_Crt_new_delete::operator new(unsigned __int64)" (__imp_??2_Crt_new_delete@std@@SAPEAX_K@Z) referenced in function "public: static unsigned __int64 __cdecl std::collate<char>::_Getcat(class std::locale::facet const * *,class std::locale const *)" (?_Getcat@?$collate@D@std@@SA_KPEAPEBVfacet@locale@2@PEBV42@@Z) [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static void __cdecl std::_Crt_new_delete::operator delete(void *)" (__imp_??3_Crt_new_delete@std@@SAXPEAX@Z) referenced in function "protected: virtual void * __cdecl std::collate<char>::`scalar deleting destructor'(unsigned int)" (??_G?$collate@D@std@@MEAAPEAXI@Z) [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : error LNK2019: unresolved external symbol __imp__CrtSetReportFile referenced in function "void __cdecl f_b_flatbuffers::SetupDefaultCRTReportMode(void)" (?SetupDefaultCRTReportMode@f_b_flatbuffers@@YAXXZ) [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : error LNK2019: unresolved external symbol __imp__CrtSetReportMode referenced in function "void __cdecl f_b_flatbuffers::SetupDefaultCRTReportMode(void)" (?SetupDefaultCRTReportMode@f_b_flatbuffers@@YAXXZ) [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\Release\firebase_core_plugin.dll : fatal error LNK1120: 9 unresolved externals [C:\Projects\flutter_repros\core_windows\next\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
Building Windows application...
Build process failed.
```

</details>

**Comment by rayliverified** [comment]
Awesome that it's reproducible! Firebase strikes again :/

@danagbemava-nc, thank you for not dismissing the problem out of hand. And one thing I, and other developers most likely can do better is creating minimal reproducible samples.

**Comment by Tanthus** [comment]
Reread this thread hoping to find a workaround or solution to this issue.  Was able to get it to get everything to compile by installing Visual Studio 2022 edition with the c++ tools, I had the 2019 edition installed.

**Comment by shdinu** [comment]
I am also facing the build error on VSCode on my machine only. Same code is running on my colleague. Following is my case
**Dependency:** 
- firebase_core: ^2.4.0
- firebase_auth: ^4.2.3
- firebase_analytics: ^10.0.8 

**Doctor summary (to see all details, run flutter doctor -v):**

- [√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1702], locale en-IN)
- [√] Windows Version (Installed version of Windows is version 10 or higher)
- [√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
- [√] Chrome - develop for the web
- [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
- [√] Android Studio (version 2021.3)
- [√] VS Code (version 1.79.1)
- [√] Connected device (3 available)
- [√] HTTP Host Availability

I am able to build windows app with same pubspec.yaml in 7th June 2023 repository but build is failing in latest repository from 13th June 2023.

This is pubspec.yaml change
![image](https://github.com/firebase/flutterfire/assets/3717720/75777e5e-e953-4bfb-98ff-18a2ff16cc85)

The change I noticed between working repository and  and non working repository is this:
![image](https://github.com/firebase/flutterfire/assets/3717720/194e8e6e-5c62-4a4a-8655-0084c9ca1144)

I also tried trued following things but no luck:

- flutter clean
- flutter pub cache clean
- Restart VSCode
- Restart windows machine
- Upgrade firebase_core to 2.14.0

**Comment by Sugihey** [comment]
I've solved this issue with update VisualStudioBuildTools2019 to version 16.11.27.

**Comment by DionJChapman** [comment]
> I've solved this issue with update VisualStudioBuildTools2019 to version 16.11.27.

I have tried updated to lates VisualStudio Tools and tried again but still getting the following issues.

`firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "struct f_b_flatbuffers::StructDef * * __cdecl __std_find_trivial<struct f_b_flatbuffers::StructDef *,unsigned __int64>(struct f_b_flatbuffers::StructDef * *,struct f_b_flatbuffers::StructDef * *,unsigned __int64)" (??$__std_find_trivial@PEAUStructDef@f_b_flatbuffers@@_K@@YAPEAPEAUStructDef@f_b_flatbuffers@@PEAPEAU01@0_K@Z) [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8 [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z) [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\Debug\firebase_core_plugin.dll : fatal error LNK1120: 2 unresolved externals [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
Exception: Build process failed.`

**Comment by Levi-Lesches** [comment]
Just to clarify, there seem to be two issues here: 
- The failed NuGet installation, shown in the top comment
- The linker errors, shown in the comment above this one

Are _both_ resolved by upgrading to Visual Studio 2022?

**Comment by DionJChapman** [comment]
I tried versions of firebase_core 2.9.0 to 2.14.0 and still have this error. I feel this is a missing dependency or DLL. But I can't find a download for trivial anywhere.

**Comment by YarostheLaunchpadder** [comment]
Does anyone know how to fix this?

**Comment by Lyokone** [comment]
Hello, we are in the process of adding Windows support. Overriding to version 2.10.0 when building for windows might help will I'm looking into the issue.

**Comment by DionJChapman** [comment]
Windows 11 Build 22000.2057

VSCode
Version: 1.80.0 (user setup)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T15:06:02.407Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22000





flutter doctor -v
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22000.2057], locale en-AU)
    • Flutter version 3.10.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Owner\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\Owner\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.31019.35
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.80.0)
    • VS Code at C:\Users\Owner\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2057]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.35

[√] Network resources
    • All expected network resources are available.

• No issues found

**Comment by crimesp** [comment]
Confirming above works - installing  "C++/CLI support for v143.." and doing a clean resolved the issue. I'm running a brand new clean machine with win 11 + flutter 3.10.6 + firebase_core 2.13.1 

Perhaps this should be added this as a pre-req on https://docs.flutter.dev/get-started/install/windows in addition to the C++ workflow reqs for VS 2022

**Comment by DionJChapman** [comment]
I can confirm that this works with compiling the app, but...

use this for the initializing Firebase
`await Firebase.initializeApp(
// Replace with actual values
options: const FirebaseOptions(
  apiKey: "api key here",
  appId: "app id here",
  messagingSenderId: "messaging id",
  projectId: "project id here",
),`

Use your settings from the Web app on the Firebase Site.
I am using these versions of the packages
firebase_auth: ^4.7.1
cloud_functions: ^4.3.4
firebase_core: ^2.15.0

Also, delete the build\windows directory, then rebuild

But now I am getting this error (I have permitted in my firewall)
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseAuthHostApi.registerIdTokenListener`

**Comment by Levi-Lesches** [comment]
I believe to actually get it working you'll need https://pub.dev/packages/firebase_core_desktop

**Comment by DionJChapman** [comment]
> I believe to actually get it working you'll need to explicitly include https://pub.dev/packages/firebase_core_desktop and https://pub.dev/packages/firebase_auth_desktop

Are you able to send me a list of your dependencies as I am having issues finding a version combination that works

**Comment by Levi-Lesches** [comment]
Try: 
```yaml
dependencies:
  firebase_auth: ^3.11.2
  firebase_auth_desktop: ^1.0.2
  firebase_core: ^1.24.0
  firebase_core_desktop: ^1.0.2
  flutter:
    sdk: flutter
```

**Comment by DionJChapman** [comment]
> ```yaml
> 1.24.0
> ```

That helped, but I am using intl 1.18.0 which flutter requires so I get this

Because every version of flutter_localization depends on flutter_localizations from sdk which depends on intl 0.18.0, every version of flutter_localization requires intl 0.18.0.
And because firebase_auth ^3.11.2 depends on firebase_auth_web ^4.6.1 which depends on intl ^0.17.0, flutter_localization is incompatible with firebase_auth ^3.11.2.
So, because platformtodo depends on both firebase_auth ^3.11.2 and flutter_localization ^0.1.12, version solving failed.

**Comment by victorlamarck** [comment]
I solve this problem updating Visual Studio version. Not the VS Code, but Visual Studio. My version was 2019 and I have updated to 2022.

**Comment by arashAndroid** [comment]
I am facing the same issue. I installed the "C++/CLI support for v143" on my VS 2022 but that did not fully fix the issue.
I am getting this error:
`firebase_app.lib(9df1b499e9d93fa7bea97ae713d33ce7_flatbuffers.dir_Release_idl_parser.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "struct f_b_flatbuffers::StructDef * * __cdecl __std_find_trivial<struct f_b_flatbuffers::StructDef *,struct f_b_flatbuffers::StructDef *>(struct f_b_flatbuffers::StructDef * *,struct f_b_flatbuffers::StructDef * *,struct f_b_flatbuffers::StructDef * const)" (??$__std_find_trivial@PEAUStructDef@f_b_flatbuffers@@PEAU12@@@YAPEAPEAUStructDef@f_b_flatbuffers@@PEAPEAU01@0QEAU01@@Z) [C:\projects\taskboard\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(9517b511b2df07341741fe8d83119943_firebase_app.dir_Release_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8 [C:\projects\taskboard\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_auth.lib(d48c2d5c2ee6ee6849b2a8e761eb596c_firebase_auth.dir_Release_auth.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8 [C:\projects\taskboard\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(9517b511b2df07341741fe8d83119943_firebase_app.dir_Release_heartbeat_storage_desktop.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z) [C:\projects\taskboard\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]C:\projects\taskboard\build\windows\plugins\firebase_core\Release\firebase_core_plugin.dll : fatal error LNK1120: 2 unresolved externals [C:\projects\taskboard\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]Building Windows application...                                  2053.2s
Build process failed.`

I tried adding this line to CMakeLists.txt: `set(CMAKE_BUILD_TYPE "Release")` but still getting the error.
I just upgraded my flutter. 

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22000.2176], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher) (i have win 11)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.1.5)
[!] Android Studio (not installed)
[√] VS Code, 64-bit edition (version 1.73.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.

(I am facing many errors after installing firebase dependencies in my app. after following many instructions i'm getting the error above. 
I am trying to build windows app and I do clean flutter build after each change.

**Comment by DionJChapman** [comment]
> I am facing the same issue. I installed the "C++/CLI support for v143" on my VS 2022 but that did not fully fix the issue.
> I am getting this error:

See this comment on the dependency for VSCode that you need https://github.com/firebase/flutterfire/issues/10992#issuecomment-1642114503

**Comment by arashAndroid** [comment]
@DionJChapman  as i mentioned, I have installed the "C++/CLI support for v143" on my VS 2022 (also it can be installed on VS, not the VSCODE).
I did a VS repair and it download 90MB of stuff and repaired it. then the error changed to this (hundreds of these lines):
`  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1253 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1362 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1362 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data

  [1371 bytes data]

  schannel: failed to decrypt data, need more data

  schannel: failed to decrypt data, need more data`

my VS 2022 version is 17.1.5
please help me fix this,

**Comment by arashAndroid** [comment]
I fixed my problem by upgrading my VS 2022 to latest version (17.7.0) and also installed some dependencies. But I do not know what fixed it (probably the update fixed it). Here is the list of packages I have: 
![image](https://github.com/firebase/flutterfire/assets/39775364/321ef37a-f0ed-49aa-97f2-5f2a45dd3510)

**Comment by Lyokone** [comment]
Hi, does it still happen using latest version of Firebase Core?

**Comment by gsloan2** [comment]
Having similar issue:
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
    • Flutter version 3.13.9 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (4 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\sloan\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34316.72
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\sloan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2715]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.72

[√] Network resources
    • All expected network resources are available.

• No issues found!

firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_x509asn1.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_x509asn1.obj)' or at ''; linking object as if no debug info [C:\flutter-recipeapp\recipeapplication\build\windows\runner\recipeapplication.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_dotdot.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_dotdot.obj)' or at ''; linking object as if no debug info [C:\flutter-recipeapp\recipeapplication\build\windows\runner\recipeapplication.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_vauth.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_vauth.obj)' or at ''; linking object as if no debug info [C:\flutter-recipeapp\recipeapplication\build\windows\runner\recipeapplication.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_digest.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_digest.obj)' or at ''; linking object as if no debug info [C:\flutter-recipeapp\recipeapplication\build\windows\runner\recipeapplication.vcxproj]
firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostcheck.obj) : warning LNK4099: PDB '' was not found with 'firebase_app.lib(d4b2e575872e0fa1bb01894d714f922c_libcurl.dir_Debug_hostcheck.obj)' or at ''; linking object as if no debug info [C:\flutter-recipeapp\recipeapplication\build\windows\runner\recipeapplication.vcxproj]

**Comment by danagbemava-nc** [comment]
Hi @gsloan2, what version of firebase_core are you using?
