### ISSUE TITLE
🐛 [firebase_messaging] Crashlytics on latest version (14.6.3)

### ISSUE THREAD

**Issue by gcjjyy** [firebase/flutterfire#11142]
## Bug report

Crashlytics reports a lot of errors on latest cell phones (such as Galaxy Z flip)
<img width="1227" alt="image" src="https://github.com/firebase/flutterfire/assets/39606947/94b57679-0eb5-4d67-b595-b1876b939954">

### Steps to reproduce

1. Upgrade firebase_messaging package version to 14.6.3

### Expected behavior

Crashlytics should not be reported.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.3
Flutter SDK 3.10.4

dependencies:
- build_runner 2.4.5 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.2.1 [flutter]
- cloud_firestore 4.8.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.3 [typed_data]
- dio 5.2.1+1 [async http_parser meta path]
- firebase_analytics 10.4.3 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.6.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.6.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 11.2.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_contacts 1.1.6 [flutter]
- flutter_email_sender 5.2.0 [flutter]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- fluttertoast 8.2.2 [flutter flutter_web_plugins]
- font_awesome_flutter 10.4.0 [flutter]
- freezed 2.3.5 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- freezed_annotation 2.2.0 [collection json_annotation meta]
- google_mobile_ads 2.4.0 [meta flutter visibility_detector]
- google_sign_in 6.1.4 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- heroicons 0.8.0 [flutter flutter_svg path]
- json_serializable 6.7.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- lottie 2.4.0 [archive flutter path vector_math]
- page_transition 2.0.9 [flutter]
- permission_handler 10.3.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- shared_preferences 2.1.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 4.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- url_launcher 6.1.11 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.7 [crypto]

dev dependencies:
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _fe_analyzer_shared 61.0.0 [meta]
- _flutterfire_internals 1.3.3 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.13.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- any_base 2.0.0
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- aws_rekognition_api 2.0.0 [shared_aws_api]
- basic_utils 5.5.4 [http logging json_annotation pointycastle]
- bloc 8.1.2 [meta]
- blur 3.1.0 [flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.0 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.2.0 [analyzer async build collection crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.10 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- camera 0.10.5+2 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- camera_android 0.10.8+2 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.13+2 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.5.1 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.1+4 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 5.15.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.6.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.5.0 [built_collection built_value collection matcher meta]
- collection 1.17.1
- connectycube_flutter_call_kit 2.2.4 [flutter universal_io]
- convert 3.1.1 [typed_data]
- country_dial_code 1.2.0 [flutter]
- cross_file 0.3.3+4 [js meta]
- csslib 1.0.0 [source_span]
- dart_style 2.3.1 [analyzer args path pub_semver source_span]
- dart_webrtc 1.0.17 [js platform_detect webrtc_interface]
- dbus 0.7.8 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- file_selector_linux 0.9.1+3 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.5.1 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.2 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.6.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+3 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.15.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.5.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.3 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config 4.2.3 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_remote_config_platform_interface 1.4.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.3 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.4.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.3 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.1.0
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications 14.1.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_slidable 3.0.0 [flutter]
- flutter_timezone 1.0.6 [flutter_web_plugins flutter js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- flutter_webrtc 0.9.34 [collection dart_webrtc flutter js path_provider webrtc_interface]
- frontend_server_client 3.2.0 [async path]
- geocoding 2.1.0 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geocoding_android 2.1.0 [flutter geocoding_platform_interface]
- geocoding_ios 2.1.0 [flutter geocoding_platform_interface]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator 9.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- geolocator_android 4.1.9 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.2.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.1 [js meta]
- google_maps 6.3.0 [js js_wrapping meta]
- google_maps_flutter 2.3.0 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_maps_flutter_android 2.4.15 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.2.3 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.2.7 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.0+1 [flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform]
- google_sign_in_android 6.1.16 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.2 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.1 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- graphs 2.3.1 [collection]
- html 0.15.4 [csslib source_span]
- http 0.13.6 [async http_parser meta]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.17 [archive meta xml]
- image_cropper 3.0.3 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_cropper_for_web 1.0.3 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 3.0.3 [flutter plugin_platform_interface http]
- image_picker 0.8.9 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- image_picker_android 0.8.7 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.8.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_purchase 3.1.5 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- in_app_purchase_android 0.2.5+4 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.4 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.6+4 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_review 2.0.6 [flutter in_app_review_platform_interface]
- in_app_review_platform_interface 2.0.4 [flutter url_launcher plugin_platform_interface platform]
- intl 0.17.0 [clock path]
- io 1.0.4 [meta path string_scanner]
- ipstack 0.5.1+1 [http meta pedantic flutter]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- json_annotation 4.8.1 [meta]
- libphonenumber 2.0.2 [flutter meta]
- logging 1.2.0
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- mime 1.0.4
- nested 1.0.0 [flutter]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.1.0 [path]
- package_info_plus 3.1.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.0.15 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.27 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.3 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 10.2.3 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.0 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.10.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.2 [flutter permission_handler_platform_interface]
- petitparser 5.4.0 [meta]
- pinput 2.2.31 [flutter smart_auth universal_platform]
- platform 3.1.0
- platform_detect 2.0.7 [meta pub_semver]
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 6.0.5 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rotated_corner_decoration 2.1.0+1 [flutter]
- rxdart 0.27.7
- sanitize_html 2.0.0 [html meta]
- shared_aws_api 2.0.0 [crypto http meta xml intl uuid collection]
- shared_preferences_android 2.1.4 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.2.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.2.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.2.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.1.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.2.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- short_uuids 2.0.0 [any_base uuid]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- smart_auth 1.0.8 [flutter flutter_web_plugins]
- smooth_page_indicator 1.1.0 [flutter]
- source_gen 1.3.2 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.2.8+4 [flutter sqflite_common path]
- sqflite_common 2.4.5+1 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- styled_text 7.0.0 [flutter xmlstream]
- syncfusion_flutter_core 21.2.10 [vector_math flutter]
- syncfusion_flutter_sliders 21.2.4 [flutter intl syncfusion_flutter_core]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.9.2 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- unique_identifier 0.3.0 [flutter]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.35 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.17 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.6 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.7 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7 [args meta path_parsing xml vector_graphics_codec]
- vector_math 2.1.4
- visibility_detector 0.3.3 [flutter]
- watcher 1.1.0 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webrtc_interface 1.0.13
- win32 4.1.4 [ffi]
- xdg_directories 1.0.0 [meta path process]
- xml 6.3.0 [collection meta petitparser]
- xmlstream 1.0.0
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@gcjjyy 
Are you able to replicate the crash locally in debug mode after upgrading plugin version or is it coming from production app ?
Also, can you provide the crash log in text format ?

**Comment by joknjokn** [comment]
We're getting the same after upgrading to the latest yesterday:
```

# Crashlytics - Stack trace
# Platform: android
# Version: 2.16.1 (4702)
# Date: Fri Jun 16 2023 13:18:51 GMT+0200 (Centraleuropæisk sommertid)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
       at java.lang.Class.isAssignableFrom(Class.java:589)
       at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4865)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
       at android.os.Parcel.readValue(Parcel.java:4544)
       at android.os.Parcel.readValue(Parcel.java:4324)
       at android.os.Parcel.-$$Nest$mreadValue()
       at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
       at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
       at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
       at android.os.BaseBundle.getValue(BaseBundle.java:374)
       at android.os.BaseBundle.getValue(BaseBundle.java:357)
       at android.os.BaseBundle.get(BaseBundle.java:696)
       at android.os.Bundle.getParcelable(Bundle.java:947)
       at android.content.Intent.getParcelableExtra(Intent.java:9558)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:31)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:2)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Firebase Background Thread #2:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:12)
       at java.lang.Thread.run(Thread.java:1012)

Firebase Background Thread #1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:12)
       at java.lang.Thread.run(Thread.java:1012)

Firebase-Messaging-Topics-Io:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1176)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:1012)

Firebase Background Thread #0:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:12)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerWatchdogDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:385)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:365)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

com.google.firebase.crashlytics.startup1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:2)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:5)
       at java.lang.Thread.run(Thread.java:1012)

pool-26-thread-1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1176)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

awaitEvenIfOnMainThread task continuation executor1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:2)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:5)
       at java.lang.Thread.run(Thread.java:1012)

com.it_nomads.fluttersecurestorage.worker:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

glide-active-resources:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
       at com.bumptech.glide.load.engine.ActiveResources.cleanReferenceQueue(ActiveResources.java:6)
       at com.bumptech.glide.load.engine.ActiveResources$2.run(ActiveResources.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.bumptech.glide.load.engine.ActiveResources$1$1.run(ActiveResources.java:7)
       at java.lang.Thread.run(Thread.java:1012)

MessengerIpcClient:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1176)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:1012)

Firebase-Messaging-Init:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1176)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:1012)

Crashlytics Exception Handler1:
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:1841)
       at java.lang.Thread.getAllStackTraces(Thread.java:1909)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateThreadsList(CrashlyticsReportDataCapture.java:16)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateExecutionData(CrashlyticsReportDataCapture.java:4)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.populateEventApplicationData(CrashlyticsReportDataCapture.java:45)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsReportDataCapture.captureEventData(CrashlyticsReportDataCapture.java:44)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistEvent(SessionReportingCoordinator.java:19)
       at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.persistFatalEvent(SessionReportingCoordinator.java:32)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java:49)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsController$2.call(CrashlyticsController.java)
       at com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker$3.then(CrashlyticsBackgroundWorker.java:2)
       at com.google.android.gms.tasks.zze.run(zze.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:2)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:5)
       at java.lang.Thread.run(Thread.java:1012)

pool-12-thread-1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

ReferenceQueueDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:232)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

queued-work-looper-data:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

GmsDynamite:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.google.android.gms.dynamite.zza.run(zza.java:6)

queued-work-looper:
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

AsyncTask #1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.onHandleWork(FlutterFirebaseMessagingBackgroundService.java:63)
       at io.flutter.plugins.firebase.messaging.JobIntentService$CommandProcessor.doInBackground(:14)
       at io.flutter.plugins.firebase.messaging.JobIntentService$CommandProcessor.doInBackground(:2)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

Firebase Background Thread #3:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:12)
       at java.lang.Thread.run(Thread.java:1012)

pool-19-thread-1:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by gcjjyy** [comment]
My error is exactly same with @joknjokn's error. Firebase and Google Play Store is warning me the error is too many and critical.

It is reproduced when the FCM background notification has come.

**Comment by joknjokn** [comment]
@gcjjyy Have you experienced any symptoms when reproduced?

**Comment by gcjjyy** [comment]
> @gcjjyy Have you experienced any symptoms when reproduced?

The app is forcefully quit.

**Comment by joknjokn** [comment]
@gcjjyy Alright, that's worrying. A high percentage of our users with this new version gets this crash, according to Crashlytics.

Can you explain your reproduction steps? I didn't manage to experience it for some reason - tried receiving/clicking push notifications in different scenarios.

**Comment by gcjjyy** [comment]
@joknjokn Thank you for your replying.

Reproduct step is simple.
1. Run application on Android device "A". then the firebase messaging will be initialized.
2. Just go to background (launcher screen) on Android device "A"
3. Send push notification (fcm) from the other device (android device "B").

Then the application running on Android A is terminated. and the notification will not show.
So user cannot click the notification.
and the dart-side background notification callback function is not called.

**Comment by joknjokn** [comment]
@gcjjyy Thank you! I cannot reproduce with my Sony Xperia 5 III, but 14% of our production users are hit. This seems very severe.

**Comment by joknjokn** [comment]
If anyone knows what to downgrade to to avoid this issue, please share. At some point 14.6.2 started having another issue - maybe related to firebase_core_platform_interface: ? Or is it related to flutter-upgrade from 3.7.X to 3.10.X ?

**Comment by gcjjyy** [comment]
No errors on 14.6.1. Please refer.

**Comment by siddharthadevops** [comment]
I am experiencing the same problem. In my case, it happens with Background notifications, and when the second notification arrives. The first one is processed correctly, but when the second one arrives, this error occurs.

**Comment by gcjjyy** [comment]
> I am experiencing the same problem. In my case, it happens with data notifications, and when the second background notification arrives. The first one is processed correctly, but when the second one arrives, this error occurs.

Exactly same with me. :)

**Comment by joknjokn** [comment]
Downgrading to this removed the crashes for us:
firebase_core: 2.13.0
firebase_messaging: 14.6.1

**Comment by JoshanTandukar** [comment]
Same issue facing in firebase_messaging: 14.6.3 downgrading to 14.6.1

**Comment by joknjokn** [comment]
Update:

After downgrading to these:
firebase_core: 2.13.0
firebase_messaging: 14.6.1

We now get:
Fatal Exception: android.os.BadParcelableException
Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.o0

Much less frequent than the 14.6.3-crash, but still problematic.

**Comment by luanbatistadev** [comment]
> I am experiencing the same problem. In my case, it happens with data notifications, and when the second background notification arrives. The first one is processed correctly, but when the second one arrives, this error occurs.

Exactly, same problem here. it happens in api 33, when the second background notification arrives. Versions of firebase_messaging that I tested:
firebase_messaging: 
^14.6.1
^14.6.2
^14.6.3

**Comment by darshankawar** [comment]
> @joknjokn Thank you for your replying.
> 
> Reproduce step is simple.
> 
> 1. Run application on Android device "A". then the firebase messaging will be initialized.
> 2. Just go to background (launcher screen) on Android device "A"
> 3. Send push notification (fcm) from the other device (android device "B").
> 
> Then the application running on Android A is terminated. and the notification will not show. So user cannot click the notification. and the dart-side background notification callback function is not called.

I tried replicating using these steps on Android 33 emulator and with latest version of the plugin, but not seem to be able to replicate the reported error.

Given the number of reports, I am going ahead and labeling it for team's attention and tracking.

/cc @Lyokone

**Comment by adamm777** [comment]
i have the same problem here :(

**Comment by adamm777** [comment]
firebase_core: ^2.13.1
firebase_auth: ^4.6.2
firebase_messaging: ^14.6.3
 broadcast received for message
D/AndroidRuntime(20904): Shutting down VM
E/AndroidRuntime(20904): FATAL EXCEPTION: main
E/AndroidRuntime(20904): Process: net.codeloops.oiasis, PID: 20904
E/AndroidRuntime(20904): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
E/AndroidRuntime(20904): 	at java.lang.Class.isAssignableFrom(Class.java:589)
E/AndroidRuntime(20904): 	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4865)
E/AndroidRuntime(20904): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
E/AndroidRuntime(20904): 	at android.os.Parcel.readValue(Parcel.java:4544)
E/AndroidRuntime(20904): 	at android.os.Parcel.readValue(Parcel.java:4324)
E/AndroidRuntime(20904): 	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
E/AndroidRuntime(20904): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
E/AndroidRuntime(20904): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
E/AndroidRuntime(20904): 	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
E/AndroidRuntime(20904): 	at android.os.BaseBundle.getValue(BaseBundle.java:374)
E/AndroidRuntime(20904): 	at android.os.BaseBundle.getValue(BaseBundle.java:357)
E/AndroidRuntime(20904): 	at android.os.BaseBundle.get(BaseBundle.java:696)
E/AndroidRuntime(20904): 	at android.os.Bundle.getParcelable(Bundle.java:947)
E/AndroidRuntime(20904): 	at android.content.Intent.getParcelableExtra(Intent.java:9558)
E/AndroidRuntime(20904): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:235)
E/AndroidRuntime(20904): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:146)
E/AndroidRuntime(20904): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(20904): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(20904): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20904): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(20904): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(20904): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(20904): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20904): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(20904): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by YeltsB** [comment]
I have the same problem. The application crashes when I send a second notification through FCM. I created a new project with Flutter v3.10.5 and Dart 3.0.5 stable and integrated only Firebase Messaging and the same thing happened.

Flutter 3.10.5
Dart 3.0.5
firebase_messaging: 14.6.3
firebase_core: 2.14.0

<details open>
  <summary>Click to Expand</summary>

  I/flutter ( 7284): Handling a background message!!: 0:1687209930714401%4d2b8f6a4d2b8f6a
  D/CompatibilityChangeReporter( 7284): Compat change id reported: 160794467; UID 10168; state: ENABLED
  D/FLTFireMsgReceiver( 7284): broadcast received for message
  D/AndroidRuntime( 7284): Shutting down VM
  E/AndroidRuntime( 7284): FATAL EXCEPTION: main
  E/AndroidRuntime( 7284): Process: com.example.gc_cargo, PID: 7284
  E/AndroidRuntime( 7284): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
  E/AndroidRuntime( 7284): 	at java.lang.Class.isAssignableFrom(Class.java:589)
  E/AndroidRuntime( 7284): 	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4897)
  E/AndroidRuntime( 7284): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4804)
  E/AndroidRuntime( 7284): 	at android.os.Parcel.readValue(Parcel.java:4564)
  E/AndroidRuntime( 7284): 	at android.os.Parcel.readValue(Parcel.java:4347)
  E/AndroidRuntime( 7284): 	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
  E/AndroidRuntime( 7284): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4442)
  E/AndroidRuntime( 7284): 	at android.os.Parcel$LazyValue.apply(Parcel.java:4401)
  E/AndroidRuntime( 7284): 	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
  E/AndroidRuntime( 7284): 	at android.os.BaseBundle.getValue(BaseBundle.java:374)
  E/AndroidRuntime( 7284): 	at android.os.BaseBundle.getValue(BaseBundle.java:357)
  E/AndroidRuntime( 7284): 	at android.os.BaseBundle.get(BaseBundle.java:696)
  E/AndroidRuntime( 7284): 	at android.os.Bundle.getParcelable(Bundle.java:953)
  E/AndroidRuntime( 7284): 	at android.content.Intent.getParcelableExtra(Intent.java:8937)
  E/AndroidRuntime( 7284): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:235)
  E/AndroidRuntime( 7284): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:146)
  E/AndroidRuntime( 7284): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService$$ExternalSyntheticLambda0.run(Unknown Source:4)
  E/AndroidRuntime( 7284): 	at android.os.Handler.handleCallback(Handler.java:942)
  E/AndroidRuntime( 7284): 	at android.os.Handler.dispatchMessage(Handler.java:99)
  E/AndroidRuntime( 7284): 	at android.os.Looper.loopOnce(Looper.java:201)
  E/AndroidRuntime( 7284): 	at android.os.Looper.loop(Looper.java:288)
  E/AndroidRuntime( 7284): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
  E/AndroidRuntime( 7284): 	at java.lang.reflect.Method.invoke(Native Method)
  E/AndroidRuntime( 7284): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  E/AndroidRuntime( 7284): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  I/Process ( 7284): Sending signal. PID: 7284 SIG: 9
  Lost connection to device.
  Exited (sigterm)
</details>

**Comment by YeltsB** [comment]
I have the same problem. The application crashes when I send a second notification through FCM. I created a new project with Flutter v3.10.5 and Dart 3.0.5 stable and integrated only Firebase Messaging and the same thing happened.

Flutter 3.10.5
Dart 3.0.5
firebase_messaging: 14.6.3
firebase_core: 2.14.0

<details>
<summary>Click to Expand</summary>

I/flutter ( 7284): Handling a background message!!: 0:1687209930714401%4d2b8f6a4d2b8f6a
D/CompatibilityChangeReporter( 7284): Compat change id reported: 160794467; UID 10168; state: ENABLED
D/FLTFireMsgReceiver( 7284): broadcast received for message
D/AndroidRuntime( 7284): Shutting down VM
E/AndroidRuntime( 7284): FATAL EXCEPTION: main
E/AndroidRuntime( 7284): Process: com.example.gc_cargo, PID: 7284
E/AndroidRuntime( 7284): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
E/AndroidRuntime( 7284): at java.lang.Class.isAssignableFrom(Class.java:589)
E/AndroidRuntime( 7284): at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4897)
E/AndroidRuntime( 7284): at android.os.Parcel.readParcelableInternal(Parcel.java:4804)
E/AndroidRuntime( 7284): at android.os.Parcel.readValue(Parcel.java:4564)
E/AndroidRuntime( 7284): at android.os.Parcel.readValue(Parcel.java:4347)
E/AndroidRuntime( 7284): at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
E/AndroidRuntime( 7284): at android.os.Parcel$LazyValue.apply(Parcel.java:4442)
E/AndroidRuntime( 7284): at android.os.Parcel$LazyValue.apply(Parcel.java:4401)
E/AndroidRuntime( 7284): at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
E/AndroidRuntime( 7284): at android.os.BaseBundle.getValue(BaseBundle.java:374)
E/AndroidRuntime( 7284): at android.os.BaseBundle.getValue(BaseBundle.java:357)
E/AndroidRuntime( 7284): at android.os.BaseBundle.get(BaseBundle.java:696)
E/AndroidRuntime( 7284): at android.os.Bundle.getParcelable(Bundle.java:953)
E/AndroidRuntime( 7284): at android.content.Intent.getParcelableExtra(Intent.java:8937)
E/AndroidRuntime( 7284): at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:235)
E/AndroidRuntime( 7284): at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:146)
E/AndroidRuntime( 7284): at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime( 7284): at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 7284): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7284): at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 7284): at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7284): at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 7284): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7284): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7284): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process ( 7284): Sending signal. PID: 7284 SIG: 9
Lost connection to device.
Exited (sigterm)
</details>

**Comment by linhmanh92** [comment]
I got the same error. This error is extremely serious for users, when they open the application and switch to the background state and then open another application, they will encounter a message asking to close the application. Hope there will be a solution soon

![image](https://github.com/firebase/flutterfire/assets/18113639/b7bedb2b-e199-45ef-b9d9-192f6dcd8463)

**Comment by Silfalion** [comment]
same issue

**Comment by russellwheatley** [comment]
Thanks for the report, I'm looking into this now and I'm able to reproduce.

**Comment by adamm777** [comment]
any updates ?

**Comment by Kavinkumarsimple** [comment]
> I am experiencing the same problem. In my case, it happens with data notifications, and when the second background notification arrives. The first one is processed correctly, but when the second one arrives, this error occurs.

Exactly the same prob

**Comment by RamsayGit** [comment]
I'm also getting android crash reports of my app on my own phone after I updated to 14.6.3. Here is the log if it may help find the bug.

java.lang.NullPointerException: Attempt
to invoke virtual method 'boolean
java.lang.Class.isInterface()' on a null object reference
at
java.lang.Class.isAssignable From(Class.java:589) at
android.os.Parcel.readParcelableCreatorInternal(Pa
rcel.java:4865)
at
android.os.Parcel.readParcelableInternal(Parcel.jav
a:4778)
at android.os. Parcel.readValue(Parcel.java:4544) at android.os. Parcel.readValue(Parcel.java:4324)
at android.os.Parcel.-$ $Nest$mreadValue(Unknown Source:0)
at android.os.Parcel$LazyValue.apply(Parcel.java:442
2) at
android.os.Parcel$LazyValue.apply(Parcel.java:438
1)
at android.os.BaseBundle.getValueAt(BaseBundle.java
:394)
at
android.os.BaseBundle.getValue(BaseBundle.java:3
74)
at android.os.BaseBundle.getValue(BaseBundle.java:3
57)
at
android.os.BaseBundle.get(BaseBundle.java:696) at
android.os.Bundle.getParcelable(Bundle.java:947) at
android.content.Intent.getParcelableExtra(Intent.jav a:9558)
at
ki.e.d(FlutterFirebaseMessagingBackgroundExecut or.java:6)
at
io.flutter.plugins.firebase.messaging. FlutterFirebas eMessagingBackgroundService.l(Unknown Source:2) at
io.flutter.plugins.firebase.messaging.FlutterFirebas eMessagingBackgroundService.j(Unknown Source:0)
at ki.f.run(Unknown Source:4)
at
android.os.Handler.handleCallback(Handler.java:94
2)
at
android.os.Handler.dispatchMessage(Handler.java:
99)
at android.os.Looper.loopOnce (Looper.java:226) at android.os.Looper.loop(Looper.java:313) at
android.app.ActivityThread.main(ActivityThread.jav
a:8757)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndAr gsCaller.run(RuntimeInit.java:571)
at
com.android.internal.os.ZygoteInit.main(ZygoteInit.j ava:1067)

**Comment by jamesorie** [comment]
@russellwheatley - sorry for my ignorance, but I see this case is closed and he code is merged. What action do we have to take on the app side? Are we supposed to update any packages or otherwise?

**Comment by Silfalion** [comment]
@jamesorie I think an update will be available soon

**Comment by russellwheatley** [comment]
@jamesorie - the fix will be out in the next release 👍 .

**Comment by toco1001** [comment]
I got same issue on 14.6.1, 14.6.2.

**Comment by zeesooho** [comment]
I got same issue on 

  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^14.1.1
  firebase_core: ^2.14.0
  
i resolved with a version change.

  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^14.1.1
  firebase_core: ^2.14.0

**Comment by 1041harpreet** [comment]
i have donwgade the packages : 
 my current packages are .
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.0  
  but i am still facing issue of crash on recieving background notification second time.

**Comment by kunatastic** [comment]
@1041harpreet 

using ^ will use the latest version. You need to remove the ^ and add the specific version number you wanted to use.

You can use:

firebase_core: 2.13.1
firebase_messaging: 14.6.2

**Comment by jamesorie** [comment]
> @1041harpreet
> 
> using ^ will use the latest version. You need to remove the ^ and add the specific version number you wanted to use.
> 
> You can use:
> 
> firebase_core: 2.13.1 firebase_messaging: 14.6.2

Does this fix the discussed issue ?

**Comment by rahulsharma841990** [comment]
> 

Great, its working for me

**Comment by rahulsharma841990** [comment]
> @1041harpreet
> 
> using ^ will use the latest version. You need to remove the ^ and add the specific version number you wanted to use.
> 
> You can use:
> 
> firebase_core: 2.13.1 firebase_messaging: 14.6.2

Nice, its working for me

**Comment by russellwheatley** [comment]
Latest messaging has been released with fix: https://pub.dev/packages/firebase_messaging
