### ISSUE TITLE
🐛 [firebase_core_web] Build failed after upgrade to 2.11.0, firebase_core 2.25.0

### ISSUE THREAD

**Issue by xurc** [firebase/flutterfire#12235]
## Bug report

**Describe the bug**
Build for web failed with

```
Target dart2js failed: ProcessException: Process exited abnormally:
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:8:2:
Error: 'JS' is imported from both 'dart:_js_annotations' and 'dart:js_interop'.
@JS()
 ^^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:17:2:
Error: 'JS' is imported from both 'dart:_js_annotations' and 'dart:js_interop'.
@JS('Promise')
 ^^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:23:2:
Error: 'JS' is imported from both 'dart:_js_annotations' and 'dart:js_interop'.
@JS()
 ^^
/root/.pub-cache/hosted/pub.dev/go_router-13.1.0/lib/src/information_provider.dart:128:34:
Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
      location: routeInformation.location!,
                                 ^
/root/.pub-cache/hosted/pub.dev/go_router-13.1.0/lib/src/parser.dart:89:50:
Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
        configuration.findMatch(routeInformation.location!, extra: state.extra);
                                                 ^
/root/.pub-cache/hosted/pub.dev/cross_file-0.3.3+8/lib/src/types/html.dart:136:42:
Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
    if (isSafari() && _length != null && _length! >= _fourGigabytes) {
                                         ^
/root/.pub-cache/hosted/pub.dev/easy_sticky_header-1.0.5/lib/src/sticky_container_widget.dart:153:37:
Warning: Operand of null-aware operation '?.' has type 'ScrollableState' which excludes null.
 - 'ScrollableState' is from 'package:flutter/src/widgets/scrollable.dart' ('/sdks/flutter/packages/flutter/lib/src/widgets/scrollable.dart').
    var scrollPosition = Scrollable.of(context)?.position;
                                    ^
/root/.pub-cache/hosted/pub.dev/easy_sticky_header-1.0.5/lib/src/render_sticky_container.dart:74:47:
Warning: Operand of null-aware operation '?.' has type 'RenderAbstractViewport' which excludes null.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('/sdks/flutter/packages/flutter/lib/src/rendering/viewport.dart').
        _pixelsCache = RenderAbstractViewport.of(this)
                                              ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:19:12:
Error: Only JS interop members may be 'external'.
  external PromiseJsImpl(Function resolver);
           ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:20:26:
Error: Only JS interop members may be 'external'.
  external PromiseJsImpl then([Func1? onResolve, Func1? onReject]);
                         ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:25:7:
Error: `@staticInterop` classes should also have the `@JS` annotation.
class JSError {}
      ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:28:26:
Error: JS interop or Native class required for 'external' extension members.
  external JSString? get name;
                         ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:29:26:
Error: JS interop or Native class required for 'external' extension members.
  external JSString? get message;
                         ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:30:26:
Error: JS interop or Native class required for 'external' extension members.
  external JSString? get code;
                         ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:32:26:
Error: JS interop or Native class required for 'external' extension members.
  external JSString? get stack;
                         ^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.0/lib/src/interop/utils/es6_interop.dart:35:22:
Error: JS interop or Native class required for 'external' extension members.
  external JSAny get customData;
                     ^
Error: Compilation failed.
```

### Expected behavior

Build success.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22631.3085], locale ru-RU)
    • Flutter version 3.16.9 on channel stable at c:\Soft\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (6 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at c:\Soft\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Soft\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\<USER>\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34024.191
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Soft\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Connected device (4 available)
    • 22081212UG (mobile) • 90e348c8 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.3085]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 120.0.6099.225
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 121.0.2277.83

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by KonstantinidouCh** [comment]
I have a similar problem 

`../../../.pub-cache/hosted/pub.dev/cloud_firestore_web-2.8.10/lib/src/utils/web_utils.dart:71:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/cloud_firestore_platform_interface-5.7.7/lib/src/platform_interface/utils/load_bundle_task_state.dart:13:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
Failed to compile application.
`

flutter version : 3.13.2
firebase_core: ^1.22.0
firebase_messaging: ^13.0.1

**Comment by supratim1609** [comment]
I faced a similar issue try : run this command first **flutter pub upgrade --major-versions**
then run this one **flutter pub outdated**

**Comment by KonstantinidouCh** [comment]
> I faced a similar issue try : run this command first **flutter pub upgrade --major-versions** then run this one **flutter pub outdated**

In my case it's not possible because many plugins have conflicts between them and I have to use specific versions for my project to run.

**Comment by walsha2** [comment]
# Workaround

See: https://github.com/firebase/flutterfire/issues/12237#issuecomment-1919614011

**Comment by darshankawar** [comment]
Everyone facing the issue, a similar [issue](https://github.com/firebase/flutterfire/issues/12237) has been fixed recently. Check the same and see if it helps to resolve your issues.

**Comment by xurc** [comment]
> Everyone facing the issue, a similar [issue](https://github.com/firebase/flutterfire/issues/12237) has been fixed recently. Check the same and see if it helps to resolve your issues.

There is still a same build error in firebase_core_web version 2.11.1

**Comment by xurc** [comment]
In version 2.11.2 the error persists, but in a different file, now in /lib/src/interop/app_interop.dart instead of /lib/src/interop/utils/es6_interop.dart

```
Target dart2js failed: ProcessException: Process exited abnormally:
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.2/lib/src/interop/app_interop.dart:8:2:
Error: 'JS' is imported from both 'dart:_js_annotations' and 'dart:js_interop'.
@JS('firebase_core')
 ^^
/root/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.2/lib/src/interop/app_interop.dart:17:2:
Error: 'JS' is imported from both 'dart:_js_annotations' and 'dart:js_interop'.
@JS('FirebaseApp')
 ^^
```
