### ISSUE TITLE
🐛 [flutter_core_web] The method 'callMethod' isn't defined for the class 'TrustedScriptURL'

### ISSUE THREAD

**Issue by M1chlCZ** [firebase/flutterfire#12242]
## Bug report

**Describe the bug**
Basically I am just unable to compile my app to Flutter web

### Steps to reproduce

Just be on Flutter Beta v3.19.0.0.13-pre and try to compile to the web version

### Expected behavior

Well that it should compile

---

## Additional context

Just that I have these Firebase dependencies

  firebase_messaging: ^14.7.11
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  firebase_analytics: ^10.8.1

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel beta, 3.19.0-0.3.pre, on macOS 14.3 23D56 darwin-arm64, locale cs-CZ)
    • Flutter version 3.19.0-0.3.pre on channel beta at /Users/m1chl/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1b197762c5 (6 days ago), 2024-01-25 22:23:26 -0800
    • Engine revision 968e2945c7
    • Dart version 3.3.0 (build 3.3.0-279.2.beta)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/m1chl/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/m1chl/Library/Android/sdk
    • Java binary at: /Users/m1chl/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/m1chl/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- auto_size_text 3.0.0 [flutter]
- awesome_snackbar_content 0.1.3 [flutter_svg flutter flutter_localizations]
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- calendar_date_picker2 0.5.3 [flutter]
- carousel_slider 4.2.1 [flutter]
- clipboard 0.1.3 [flutter]
- country_code_picker 3.0.0 [flutter collection]
- country_icons 3.0.0 [flutter flutter_svg]
- country_picker 2.0.24 [collection universal_io flutter]
- cron 0.6.0 [clock]
- cron_form_field 0.6.0 [flutter]
- csslib 1.0.0 [source_span]
- csv 5.1.1
- custom_clippers 2.0.0 [flutter]
- desktop_drop 0.4.4 [flutter flutter_web_plugins cross_file]
- dio 5.4.0 [async http_parser meta path]
- dotted_border 2.1.0 [flutter path_drawing]
- dropdown_button2 2.3.9 [flutter meta]
- easy_cron 0.9.2 [equatable]
- easy_localization 3.0.3 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- equatable 2.0.5 [collection meta]
- expansion_widget 0.0.3 [flutter]
- ferry 0.15.0+1 [gql rxdart gql_link gql_exec meta collection hive built_value ferry_exec normalize ferry_cache]
- ferry_flutter 0.9.0 [ferry gql_exec ferry_exec flutter flutter_test]
- ferry_generator 0.9.1-dev.1 [gql gql_code_builder gql_tristate_value built_collection code_builder build path ferry_exec yaml dart_style glob built_value_generator built_value analyzer]
- firebase_analytics 10.8.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.17.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.25.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.11 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- fl_chart 0.66.1 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_countdown_timer 4.1.0 [flutter]
- flutter_hooks 0.20.4 [flutter]
- flutter_inappwebview 6.0.0 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_screenutil 5.9.0 [flutter]
- flutter_spinkit 5.2.0 [flutter]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_switch 0.3.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- go_router 13.1.0 [collection flutter flutter_web_plugins logging meta]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- gql 1.0.0+1 [collection meta source_span yaml]
- gql_http_link 1.0.1+1 [gql gql_exec gql_link http http_parser meta]
- gql_websocket_link 2.0.1 [gql gql_exec gql_link meta rxdart uuid web_socket_channel]
- hexcolor 3.0.1 [flutter flutter_web_plugins]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- hive_generator 2.0.1 [build source_gen hive analyzer source_helper]
- hooks_riverpod 2.4.9 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- horizontal_blocked_scroll_physics 4.0.1 [flutter]
- image_picker 1.0.7 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- infinite_scroll_pagination 4.0.0 [flutter flutter_staggered_grid_view sliver_tools]
- intl_phone_field 3.2.0 [flutter]
- intl_phone_number_input 0.7.4 [flutter libphonenumber_plugin equatable collection]
- json_annotation 4.8.1 [meta]
- loading_indicator 3.1.1 [flutter async collection]
- lottie 3.0.0 [archive flutter path vector_math]
- marquee 2.2.3 [fading_edge_scrollview flutter]
- mask_text_input_formatter 2.8.0 [flutter]
- number_paginator 0.4.1 [auto_size_text flutter]
- open_file 3.3.2 [flutter ffi]
- package_info_plus 5.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- percent_indicator 4.2.3 [flutter]
- permission_handler 11.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- pie_chart 5.4.0 [flutter]
- pin_code_fields 8.0.1 [flutter]
- pinput 3.0.1 [flutter smart_auth universal_platform]
- qr_flutter 4.1.0 [flutter qr]
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- slide_action 0.0.2 [flutter]
- slider_captcha 1.0.0 [flutter]
- sliding_up_panel 2.0.0+1 [flutter]
- syncfusion_flutter_charts 24.2.3 [flutter intl vector_math syncfusion_flutter_core]
- syncfusion_flutter_core 24.2.3 [vector_math flutter]
- syncfusion_flutter_datepicker 24.2.3 [flutter intl syncfusion_flutter_core]
- theme_provider 0.6.0 [flutter shared_preferences]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_image_picker_web 0.0.1 [flutter flutter_web_plugins universal_html]
- url_launcher 6.2.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_strategy 0.2.0 [flutter_web_plugins]
- web_socket_channel 2.4.3 [async crypto stream_channel web]

dev dependencies:
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- build_runner 2.4.8 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- flutter_lints 3.0.1 [lints]
- flutter_native_splash 2.3.10 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml ansicolor]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.17 [collection firebase_core firebase_core_platform_interface flutter meta]
- ansicolor 2.0.2
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- built_collection 5.1.1
- built_value 8.8.1 [built_collection collection fixnum meta]
- built_value_generator 8.8.1 [analyzer build build_config built_collection built_value collection source_gen]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+8 [meta web]
- crypto 3.0.3 [typed_data]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- easy_logger 0.0.2 [flutter]
- fading_edge_scrollview 3.0.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ferry_cache 0.8.0 [ferry_exec meta rxdart normalize ferry_store collection pedantic]
- ferry_exec 0.5.0 [gql gql_exec gql_link meta async collection built_collection built_value]
- ferry_store 0.5.3 [rxdart collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.9.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+13 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.1.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.9.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_messaging_platform_interface 4.5.19 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.6.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_inappwebview_android 1.0.12 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.1.1
- flutter_inappwebview_ios 1.0.13 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.0.11 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.0.10 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.0.8 [flutter flutter_web_plugins js flutter_inappwebview_platform_interface]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_riverpod 2.4.9 [collection flutter meta riverpod state_notifier]
- flutter_staggered_grid_view 0.7.0 [flutter]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.0+2 [meta web]
- google_sign_in_android 6.1.21 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.3 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.3+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- gql_code_builder 0.10.0 [analyzer built_collection built_value code_builder collection gql gql_exec path gql_tristate_value]
- gql_exec 1.0.0+1 [collection gql meta]
- gql_link 1.0.0+1 [gql gql_exec meta]
- gql_tristate_value 1.0.0
- graphs 2.3.1 [collection]
- html 0.15.4 [csslib source_span]
- http 1.2.0 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.4 [archive meta xml]
- image_picker_android 0.8.9+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.18.1 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- libphonenumber_platform_interface 0.4.2 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.3.3 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web]
- libphonenumber_web 0.3.2 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.4
- normalize 0.9.0 [gql collection]
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 12.0.3 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.3.0 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.1.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- riverpod 2.4.9 [meta stack_trace state_notifier]
- rxdart 0.27.7
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- sliver_tools 0.2.12 [flutter]
- smart_auth 1.1.1 [flutter flutter_web_plugins]
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0+2 [synchronized path meta]
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_android 6.2.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.1 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.9+2 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.9+2
- vector_graphics_compiler 1.1.9+2 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.4.2
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

---

**Comment by RoarGronmo** [comment]
This problem arose after "pub upgrade" today on:
`[√] Flutter (Channel beta, 3.19.0-0.3.pre, on Microsoft Windows [Version 10.0.22631.3007], locale nb-NO)`

Here are the upgrade results:
```
PS C:\FlutterProjects\mwork> flutter pub upgrade
Resolving dependencies... (12.1s)
> _fe_analyzer_shared 67.0.0 (was 66.0.0)
> _flutterfire_internals 1.3.17 (was 1.3.16)
> analyzer 6.4.1 (was 6.4.0)
> build_runner_core 7.3.0 (was 7.2.11)
> chopper 7.1.1 (was 7.1.0+1)
> device_info_plus 9.1.2 (was 9.1.1)
> ffi 2.1.2 (was 2.1.0)
> firebase_core 2.25.0 (was 2.24.2)
> firebase_core_web 2.11.0 (was 2.10.0)
> firebase_crashlytics 3.4.10 (was 3.4.9)
> firebase_crashlytics_platform_interface 3.6.17 (was 3.6.16)
> firebase_performance 0.9.3+9 (was 0.9.3+8)
> firebase_performance_platform_interface 0.1.4+17 (was 0.1.4+16)
> firebase_performance_web 0.1.4+17 (was 0.1.4+16)
  flutter_lints 2.0.3 (3.0.1 available)
> image 4.1.6 (was 4.1.4)
  intl 0.18.1 (0.19.0 available)
  js 0.6.7 (0.7.0 available)
  leak_tracker 10.0.0 (10.0.3 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.2 available)
  leak_tracker_testing 2.0.1 (3.0.0 available)
  lints 2.1.1 (3.0.0 available)
> swagger_dart_code_generator 2.15.0 (was 2.14.2)
  test_api 0.6.1 (0.7.0 available)
  vm_service 13.0.0 (14.0.0 available)
Changed 16 dependencies!

```
It is a showstopper at the moment for us...

**Comment by darshankawar** [comment]
Everyone facing the issue, a similar one https://github.com/firebase/flutterfire/issues/12237 has been fixed recently. Check the same and see if it helps to resolve your issues.

**Comment by darshankawar** [comment]
Revisiting this and observed that using latest `firebase_core_web` and `firebase_core` versions, running the core example on web gives me same error as reported.

https://github.com/firebase/flutterfire/issues/12235#issuecomment-1921146702

/cc @Lyokone

**Comment by RoarGronmo** [comment]
Still an issue with firebase_core_web v2.11.2.
![image](https://github.com/firebase/flutterfire/assets/11217296/2fdc774c-3762-4188-9bf9-963bfe5ad156)

**Comment by Lyokone** [comment]
Hi, seems that something changed in web 0.4.2, using stable version we are resolving on 0.3.0. Let me see if I can go around this issue. Can you confirm that using stable you don't run into issues?

**Comment by RoarGronmo** [comment]
Not sure at writing moment, but here is my current pubspec.yaml of the project that has this issue.

Note ! At the moment `firebase_core_web: 2.10.0 ` is pinned to this version to avoid the problem.

```
name: mwork
description: A tool for handling orders in Norva24.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.5+53

environment:
  #sdk: ">=2.16.0-80.1.beta <4.0.0"
  #sdk: ">=2.17.0 <4.0.0"
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  #_fe_analyzer_shared: 51.0.0
  #analyzer: ^6.2.0
  #camera_web: ^0.3.0
  #characters: ^1.2.1
  #material_color_utilities: ^0.1.5

  #webview_flutter: 4.0.1


  #flutter_webview_plugin:
  #  git: https://github.com/nuc134r/flutter_webview_plugin.git

  msal_js: ^2.14.0

  #--- aad-oauth Azure Active Directory login by Earlybyte ---
  aad_oauth: ^1.0.0
  #aad_oauth:
  #  git: https://github.com/Earlybyte/aad_oauth.git


  provider: ^6.0.3
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  #introduction_screen: ^3.0.2
  intl: ^0.18.0
  #socket_io_client: ^2.0.0-beta.4-nullsafety.0


  #--jwt--- makes it possible to analyze jwt
  jwt_decode: ^0.3.1

  #---Swagger changes---
  chopper: ^7.0.8
  json_annotation: ^4.5.0

  #---Google Maps---
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  google_static_maps_controller: ^1.0.0

  #---Pointer interceptor
  pointer_interceptor: ^0.10.0

  #---Location data (GPS)---
  #location: ^4.4.0
  location: ^5.0.2+1

  #---Get---
  get: ^4.6.5

  #---Flutter Bloc---
  flutter_bloc: ^8.0.1

  #---Settings / preferences ---
  #flutter_settings_screens: ^0.3.2-null-safety
  shared_preferences: ^2.2.1
  #pref: ^2.6.0

  #---Camera function---
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  path: ^1.8.3

  #---image_picker function
  image_picker: ^1.0.2
  image_picker_for_web: ^3.0.0

  #---Floor functionality---
  #floor: ^1.2.0

  #---Drift functionality---
  drift: ^2.3.0
  #drift:
  #  git:
  #    url: https://github.com/simolus3/drift.git
  #    ref: develop
  #    path: drift
  #drift: 1.7.1
  sqlite3_flutter_libs: ^0.5.7
  sqlite3: ^2.3.0


  #---Url launcher
  url_launcher: ^6.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  animated_rotating_widget: ^0.0.2

  #---badges for icons
  #badges: ^3.0.1

  #---flutter webview plugin displace
  #flutter_webview_plugin:
  #    git: https://github.com/nuc134r/flutter_webview_plugin.git

  #---logging:
  logging: ^1.0.2
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.1
  firebase_core_web: 2.10.0
  #package_info_plus: ^5.0.0
  package_info_plus: ^5.0.1
  firebase_performance: ^0.9.0+1

  #---db_inspector
  drift_db_viewer: ^2.0.0

  #---validators
  email_validator: ^2.1.17

  #---list extensions
  collection: ^1.16.0

  #---flag
  flag: ^7.0.0

  #---data table 2
  data_table_2: ^2.4.2

  #---devuce info plus
  #device_info_plus: ^10.0.0
  device_info_plus: ^9.1.0
  label_marker: ^1.0.1
  custom_info_window: ^1.0.1

  #---file picker
  file_picker: ^6.0.0

  #---http
  http: ^1.1.0
  http_parser: ^4.0.2

  #---dio
  dio: ^5.3.2

  #---exif
  exif: ^3.1.4

  #---flutter_media_metadata
  #flutter_media_metadata: 1.0.0+1

  #---date_util
  #date_util: 0.1.4

  #---flutter_native_splash
  #flutter_native_splash: ^2.2.16


  #---Animated splashscreen:
  #animated_splash_screen: ^1.3.0
#---Icons---



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_round.png"
  adaptive_icon_background: "#666666"

dev_dependencies:
  flutter_test:
    sdk: flutter

  #---swagger changes---
  build_runner: ^2.1.11
  chopper_generator: ^7.0.5+1
  json_serializable: ^6.2.0
  swagger_dart_code_generator: ^2.8.7

  #---Launcher icons---
  flutter_launcher_icons: ^0.13.0

  #---floor generators---
  #floor_generator: ^1.2.0

  #---drift generators---
  drift_dev: ^2.3.0
  #drift_dev: 1.7.1

  #--- analyzer
  #analyzer: ^4.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  #flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



```

and when running `flutter pub get` i get:

```
PS C:\FlutterProjects\mwork> flutter pub get
Resolving dependencies... (4.2s)
  _flutterfire_internals 1.3.16 (1.3.19 available)
  firebase_core 2.24.2 (2.25.2 available)
  firebase_core_web 2.10.0 (2.11.2 available)
  firebase_crashlytics 3.4.9 (3.4.12 available)
  firebase_crashlytics_platform_interface 3.6.16 (3.6.19 available)
  firebase_performance 0.9.3+8 (0.9.3+11 available)
  firebase_performance_platform_interface 0.1.4+16 (0.1.4+19 available)
  firebase_performance_web 0.1.4+16 (0.1.4+19 available)
  flutter_lints 2.0.3 (3.0.1 available)
  intl 0.18.1 (0.19.0 available)
  js 0.6.7 (0.7.0 available)
  leak_tracker 10.0.0 (10.0.3 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.2 available)
  leak_tracker_testing 2.0.1 (3.0.0 available)
  lints 2.1.1 (3.0.0 available)
  test_api 0.6.1 (0.7.0 available)
  vm_service 13.0.0 (14.0.0 available)
Got dependencies!

```

and running `flutter pub outdated` I get this
```
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name          Current   Upgradable  Resolvable  Latest

direct dependencies:
firebase_core         *2.24.2   *2.24.2     2.25.2      2.25.2
firebase_core_web     *2.10.0   *2.10.0     2.11.2      2.11.2
firebase_crashlytics  *3.4.9    *3.4.9      3.4.12      3.4.12
firebase_performance  *0.9.3+8  *0.9.3+8    0.9.3+11    0.9.3+11
intl                  *0.18.1   *0.18.1     *0.18.1     0.19.0

dev_dependencies:
flutter_lints         *2.0.3    *2.0.3      *2.0.3      3.0.1

4  dependencies are constrained to versions that are older than a resolvable version.

```
--and of course `firebase` entries are otudated because of pinnng `firebase_core_web`

`flutter doctor` has this contents:
```
PS C:\FlutterProjects\mwork> flutter doctor -v
[√] Flutter (Channel beta, 3.19.0-0.3.pre, on Microsoft Windows [Version 10.0.22631.3007], locale nb-NO)
    • Flutter version 3.19.0-0.3.pre on channel beta at c:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1b197762c5 (7 days ago), 2024-01-25 22:23:26 -0800
    • Engine revision 968e2945c7
    • Dart version 3.3.0 (build 3.3.0-279.2.beta)
    • DevTools version 2.31.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\RoarGronmo\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android Studio\Android Studio 2023.3.1.6\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11255266)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android Studio\Andruid Studio 2023.3.1.5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.1.1.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.2.1.18
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android Studio\Android Studio 2023.3.1.6
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11255266)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.83

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

At the moment the remedy is to pin `firebase_core_web` to `2.10.0` as shown above.

---

The project has so many aspects pinning to the beta version at the moment, I cannot revert to stable, but I'll try to pin `web 0.3.0` somehow, if I can manage it...

**Comment by RoarGronmo** [comment]
Checked with `web 0.3.0` but it didn't sort out.

1. Because some of my own libraries complains (maybe level of web dependency).
2. And still a problem with `callMethod`...:

(2.)
```
[+1948 ms] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.11.2/lib/src/firebase_core_web.dart:135:66: Error: The method 'callMethod' isn't defined for the class 'TrustedScriptURL'.
[        ]  - 'TrustedScriptURL' is from 'package:web/src/dom/trusted_types.dart' ('/C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/trusted_types.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'callMethod'.
[        ]         callback(await import("${trustedUrl != null ? trustedUrl.callMethod('toString'.toJS) : src}"));
[        ]                                                                  ^^^^^^^^^^
[+3293 ms] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/helpers/events/providers.dart:615:9: Error: The method 'typeofEquals' isn't defined for the class 'EventTarget'.
[        ]  - 'EventTarget' is from 'package:web/src/dom/dom.dart' ('/C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/dom.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'typeofEquals'.
[        ]   if (e.typeofEquals('undefined')) {
[        ]         ^^^^^^^^^^^^
[        ] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/helpers/events/providers.dart:617:16: Error: The method 'hasProperty' isn't defined for the class 'EventTarget'.
[        ]  - 'EventTarget' is from 'package:web/src/dom/dom.dart' ('/C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/dom.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'hasProperty'.
[        ]   } else if (e.hasProperty('mozHidden'.toJS).toDart) {
[        ]                ^^^^^^^^^^^
[   +2 ms] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/helpers/events/providers.dart:619:16: Error: The method 'hasProperty' isn't defined for the class 'EventTarget'.
[        ]  - 'EventTarget' is from 'package:web/src/dom/dom.dart' ('/C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/dom.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'hasProperty'.
[        ]   } else if (e.hasProperty('msHidden'.toJS).toDart) {
[        ]                ^^^^^^^^^^^
[   +1 ms] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/helpers/events/providers.dart:621:16: Error: The method 'hasProperty' isn't defined for the class 'EventTarget'.
[        ]  - 'EventTarget' is from 'package:web/src/dom/dom.dart' ('/C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/dom.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'hasProperty'.
[        ]   } else if (e.hasProperty('webkitHidden'.toJS).toDart) {
[        ]                ^^^^^^^^^^^
```
and many others...
here's a few of them
(1.)
```
[        ] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/webxrlayers.dart:152:40: Error: The type 'JSObject' can't be used as supertype.
[        ] class XRProjectionLayerInit implements JSObject {
[        ]                                        ^
[        ] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/webxrlayers.dart:178:30: Error: The type 'JSObject' can't be used as supertype.
[        ] class XRLayerInit implements JSObject {
[        ]                              ^
[        ] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/webxrlayers.dart:305:33: Error: The type 'JSObject' can't be used as supertype.
[        ] class XRWebGLBinding implements JSObject {
[        ]                                 ^
[        ] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/webxrlayers.dart:338:35: Error: The type 'JSObject' can't be used as supertype.
[        ] class XRMediaLayerInit implements JSObject {
[        ]                                   ^
[        ] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/webxrlayers.dart:426:33: Error: The type 'JSObject' can't be used as supertype.
[        ] class XRMediaBinding implements JSObject {
[        ]                                 ^
[        ] /C:/Users/RoarGronmo/AppData/Local/Pub/Cache/hosted/pub.dev/web-0.3.0/lib/src/dom/xhr.dart:92:27: Error: The type 'JSObject' can't be used as supertype.
[        ] class FormData implements JSObject {
```

...no it didn't solve the main problem...
