### ISSUE TITLE
🐛 firebase_core_web - Error: Expected a value of type 'String', but got one of type 'Null'

### ISSUE THREAD

**Issue by GeertStev** [firebase/flutterfire#12253]
## Bug report

In an empty app setup for Firebase and Riverpod, calling Firebase.initializeApp produces the error "Error: Expected a value of type 'String', but got one of type 'Null'" when running for web.  

### Steps to reproduce

1. New app
2. CLI and flutterfire configuration
3. pub add Riverpod and Firebase
4. Call Firebase.initializeApp in main

### Sample project

```dart
void main() async {
  //Make a connection with Firebase
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.web,
  );

  //Enable Riverpod and run app
  runApp(
    const ProviderScope(
      child: MyApp(),
    ),
  );
}
``` 

---

## Additional context

<details><summary>Debug console</summary>

```
Launching lib\main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:59625/eLj2ahEmYJU=/ws
Debug service listening on ws://127.0.0.1:59625/eLj2ahEmYJU=/ws
Connecting to VM Service at ws://127.0.0.1:59625/eLj2ahEmYJU=/ws
Error: Expected a value of type 'String', but got one of type 'Null'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 127:3       castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 818:12  cast
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 674:17                as
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 81:5                      getProperty
packages/firebase_core_web/firebase_core_web.dart 35:26                           _createFromJsOptions
packages/firebase_core_web/firebase_core_web.dart 27:39                           _createFromJsApp
packages/firebase_core_web/src/firebase_core_web.dart 322:12                      initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                         [_completeWithValue]
dart-sdk/lib/async/future.dart 529:22                                             <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.3930], locale nl-NL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.3)  
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.2)      
[√] Connected device (3 available)
[√] Network resources

• No issues found! 
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.6
Flutter SDK 3.16.9
hs_coaching_client 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- firebase_core 2.25.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_riverpod 2.4.9 [collection flutter meta riverpod state_notifier]
- riverpod_annotation 2.3.3 [meta riverpod]

dev dependencies:
- build_runner 2.4.8 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- custom_lint 0.5.11 [analyzer analyzer_plugin args async ci cli_util collection freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- riverpod_generator 2.3.9 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 2.3.7 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]

transitive dependencies:
- _fe_analyzer_shared 64.0.0 [meta]
- analyzer 6.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.11.3 [analyzer collection dart_style pub_semver yaml]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.0 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- custom_lint_builder 0.5.11 [analyzer analyzer_plugin collection custom_lint custom_lint_core glob hotreloader meta package_config path pubspec_parse rxdart]
- custom_lint_core 0.5.11 [analyzer analyzer_plugin collection custom_lint matcher meta package_config path pubspec_parse source_span yaml]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- file 7.0.0 [meta path]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- fixnum 1.1.0
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.1 [collection]
- hotreloader 4.1.0 [collection logging path stream_transform vm_service watcher]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mime 1.0.5
- package_config 2.1.0 [path]
- path 1.8.3
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- riverpod 2.4.9 [meta stack_trace state_notifier]
- riverpod_analyzer_utils 0.5.0 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- rxdart 0.27.7
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_math 2.1.4
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by dacianf** [comment]
@yarmel I just tried it, and it doesn't work

```
Error: Expected a value of type 'String', but got one of type 'Null'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 127:3       castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 818:12  cast
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 674:17                as
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 81:5                      getProperty
packages/firebase_core_web/firebase_core_web.dart 34:25                           _createFromJsOptions
packages/firebase_core_web/firebase_core_web.dart 27:39                           _createFromJsApp
packages/firebase_core_web/src/firebase_core_web.dart 322:12                      initializeApp
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                         [_completeWithValue]
dart-sdk/lib/async/future.dart 529:22                                             <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
```

I need to add: `databaseURL`; `storageBucket`; `measurementId`; `authDomain` as strings there to work. That's annoying

```dart
FirebaseOptions(
      ...
      databaseURL: firebaseOptions.databaseURL ?? '',
      storageBucket: firebaseOptions.storageBucket ?? '',
      measurementId: firebaseOptions.measurementId ?? '',
      authDomain: firebaseOptions.authDomain ?? '',
)
```

**Comment by dacianf** [comment]
> @yarmel I just tried it, and it doesn't work
> 
> ```
> Error: Expected a value of type 'String', but got one of type 'Null'
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 127:3       castError
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 818:12  cast
> dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 674:17                as
> dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 81:5                      getProperty
> packages/firebase_core_web/firebase_core_web.dart 34:25                           _createFromJsOptions
> packages/firebase_core_web/firebase_core_web.dart 27:39                           _createFromJsApp
> packages/firebase_core_web/src/firebase_core_web.dart 322:12                      initializeApp
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
> dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
> dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
> dart-sdk/lib/async/future_impl.dart 846:44                                        handleValueCallback
> dart-sdk/lib/async/future_impl.dart 875:13                                        _propagateToListeners
> dart-sdk/lib/async/future_impl.dart 647:5                                         [_completeWithValue]
> dart-sdk/lib/async/future.dart 529:22                                             <fn>
> dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
> dart-sdk/lib/async/future_impl.dart 162:18                                        handleValue
> dart-sdk/lib/async/future_impl.dart 846:44                                        handleValueCallback
> dart-sdk/lib/async/future_impl.dart 875:13                                        _propagateToListeners
> dart-sdk/lib/async/future_impl.dart 647:5                                         [_completeWithValue]
> dart-sdk/lib/async/future_impl.dart 721:7                                         callback
> dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
> dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                <fn>
> ```
> 
> I need to add: `databaseURL`; `storageBucket`; `measurementId`; `authDomain` as strings there to work. That's annoying
> 
> ```dart
> FirebaseOptions(
>       ...
>       databaseURL: firebaseOptions.databaseURL ?? '',
>       storageBucket: firebaseOptions.storageBucket ?? '',
>       measurementId: firebaseOptions.measurementId ?? '',
>       authDomain: firebaseOptions.authDomain ?? '',
> )
> ```

I tried to deploy a production build on web using firebase and it doesn't even work with the above settings.
It only works in debug mode with the above config.

**Comment by hughesyadaddy** [comment]
This is super sloppy. I've been fighting with this for the last 6 hours just to find out this is an issue with the package.

**Comment by MarcVanDaele90** [comment]
> This is super sloppy. I've been fighting with this for the last 6 hours just to find out this is an issue with the package.

Same here :-(

**Comment by MartinDapper** [comment]
> This is super sloppy. I've been fighting with this for the last 6 hours just to find out this is an issue with the package.

mee too

**Comment by adar2378** [comment]
Downgrade to old firebase_core_web to resolve it until the fix is pushed

**Comment by MartinDapper** [comment]
@adar2378 which version do you had ? I did not have install firebase_core_web in the project and afer install doesnt work

**Comment by LucasDCR2** [comment]
Did Firebase Core Version 2.25.2 Resolve the Issue for Anyone? It still doesn´t work for me

**Comment by dacianf** [comment]
```dart
final firebaseOptions = DefaultFirebaseOptions.currentPlatform;
FirebaseOptions(
      apiKey: firebaseOptions.apiKey,
      appId: firebaseOptions.appId,
      messagingSenderId: firebaseOptions.messagingSenderId,
      projectId: firebaseOptions.projectId,
      databaseURL: firebaseOptions.databaseURL ?? '',
      storageBucket: firebaseOptions.storageBucket ?? '',
      measurementId: firebaseOptions.measurementId ?? '',
      authDomain: firebaseOptions.authDomain ?? '',
)
```
This solution seems to work at the moment (previously I said it doesn't work on prod, but it does, my mistake 🤦 )
Can any of you try this temp fix and then do a fresh build/run and see if it works for you?

**Comment by LucasDCR2** [comment]
That last one works for me too, thanks!

**Comment by adar2378** [comment]
> @adar2378 which version do you had ? I did not have install firebase_core_web in the project and afer install doesnt work

firebase_core: 2.24.2
firebase_core_web: 2.10.0

**Comment by GeertStev** [comment]
> ```dart
> final firebaseOptions = DefaultFirebaseOptions.currentPlatform;
> FirebaseOptions(
>       apiKey: firebaseOptions.apiKey,
>       appId: firebaseOptions.appId,
>       messagingSenderId: firebaseOptions.messagingSenderId,
>       projectId: firebaseOptions.projectId,
>       databaseURL: firebaseOptions.databaseURL ?? '',
>       storageBucket: firebaseOptions.storageBucket ?? '',
>       measurementId: firebaseOptions.measurementId ?? '',
>       authDomain: firebaseOptions.authDomain ?? '',
> )
> ```
> 
> This solution seems to work at the moment (previously I said it doesn't work on prod, but it does, my mistake 🤦 ) Can any of you try this temp fix and then do a fresh build/run and see if it works for you?

Thank you, this also works for me in prod. 👍

**Comment by NeilFawcett1** [comment]
And, this is definitely *not* already fixed. I have been working with this since the update last week that broke everything, following every fix, applying it, updating flutter and firebase every few minutes, flutter clean, flutter build web, etc. All the fixes to date have fixed one part of it: I can now log in using email and password without the string/null error occurring-- so at least I am able to debug my Web app and carry on coding just about. But the authentication using credentials calling
                                                      final credential = GoogleAuthProvider
                                                          .credential(
                                                        accessToken: googleAuth?.accessToken,
                                                        idToken: googleAuth?.idToken,
                                                      );
Still does not work despite all the fixes. My thread got closed because it has been fixed-- it hasn't. Sometimes errors happen with these big projects (although somewhat odd that a new commit was put up which broke so many builds, without I assume much testing). But telling someone who is an experienced developer that the thing works when it obviously doesn't is pretty annoying.

**Comment by dezsocsete** [comment]
I can confirm this is not fixed, with 2.25.3 and flutter 3.16.9, after startup, it displays my index.html with the loading indicator, but it never runs the flutter code because of this:

`Expected a value of type 'JavaScriptObject', but got one of type 'Null'`

With 2.25.2 it said: 
`Expected a value of type 'String', but got one of type 'Null'`
