### ISSUE TITLE
firebase_auth: Can't login on ios after updating to 5.2.0

### ISSUE THREAD

**Issue by sebastiankan** [firebase/flutterfire#13259]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

I'm getting the following error on calling verifyPhoneNumber on ios after updating to 5.2.0
FirebaseAuthException ([firebase_auth/invalid-app-credential] Token mismatch)

### Reproducing the issue

return FirebaseAuth.instance.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        codeSent: (verificationId, forceResendToken) {
          print('code sent');
          codeSent(verificationId, forceResendToken);
        },
        verificationCompleted: verificationCompleted,
        timeout: const Duration(seconds: 30),
        verificationFailed: (e) => verificationFailed(e),
        codeAutoRetrievalTimeout: (verificationId) =>
            codeAutoRetrievalTimeout(verificationId));

### Firebase Core version

3.4.0

### Flutter Version

3.24.1

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by AnkitFlutterDev** [comment]
I am also facing this same problem for only ios physical devices, in simulator send otp works fine,
i have implimented firebase_messaging: ^15.1.0 for push notification
i have read a lots of stackoverflow artical and applied all things step by step, but nothing works, which is mentioned below 
https://stackoverflow.com/questions/74340881/invalid-app-credential-token-mismatch-in-flutter-firebase-auth
https://stackoverflow.com/questions/45091583/invalid-token-when-trying-to-authenticate-phone-number-using-firebase
https://stackoverflow.com/questions/53913105/token-mismatch-using-phone-number-authentication-ios
https://stackoverflow.com/questions/57395948/flutter-firebase-phone-auth-always-returns-token-mismatch-on-ios

Please help us as soon as possible

**Comment by AnkitFlutterDev** [comment]
@sebastiankan i am also faced this same problem bro, i have just fixed at this moment so i am suggesting what i have done

Please be sure u have added this 2 things
1. you need to add the Push notification and Background modes capability with Background fetch and Remote notifications options.
2.On the Apple Developer page, need to generate a new key with Apple Push Notifications service (APNs) service and uploaded it as an APNs Authentication Key to Firebase.
according to this below artical 
https://stackoverflow.com/questions/58246620/apns-device-token-not-set-before-retrieving-fcm-token-for-sender-id-react-nati

i have made changes in my ios/AppDelegate.swift file

import UIKit
import Flutter
import FirebaseCore
import FirebaseMessaging

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {

  override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Messaging.messaging().setAPNSToken(deviceToken, type: .unknown)
  }

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

**Comment by SelaseKay** [comment]
Hi @sebastiankan , Have you tried the above fix?

**Comment by sebastiankan** [comment]
> Hi @sebastiankan , Have you tried the above fix?

Yes i tried them + many other solutions i've found by lots of search but still having the issue, I'm trying to find-out the solution. 
Till now I've figured out there was a problem on receiving auth push notification before,
I'm getting 'This fake notification should be forwarded to Firebase Auth.' on didReceiveRemoteNotification
 on previous firebase package versions when the auth notification fails it shows the recaptcha but it's not happening in 5.2.0.
 (I have checked APNs Authentication Key on firebase)
 I keep trying to fix then I'll share the final solution.
 I would be grateful if someone share a solution if already have it.

**Comment by sebastiankan** [comment]
Finally I decided to test the production environment, and there is no problem on Testflight version. 
I have no idea what's happening 🤯
I'm attaching some screenshots of my configs to make sure the problem is on my side or not.
<img width="800" alt="Screenshot 2024-09-03 at 8 59 02 PM" src="https://github.com/user-attachments/assets/ab582ed9-280c-4c8f-b573-8485c54c555e">
<img width="691" alt="Screenshot 2024-09-03 at 9 02 16 PM" src="https://github.com/user-attachments/assets/ab02b50d-72bf-4e7d-a7f9-f1870f40de6b">
<img width="742" alt="Screenshot 2024-09-03 at 9 04 29 PM" src="https://github.com/user-attachments/assets/99d0c660-efcd-4db8-8bdc-e4b0aff4b666">
<img width="808" alt="Screenshot 2024-09-03 at 9 06 07 PM" src="https://github.com/user-attachments/assets/a0a8b7a9-a98c-4a22-b599-8890a80d81a9">

**Comment by Tpow99** [comment]
@sebastiankan I have resolved this on my end with this section of the iOS+ documentation: 

![image](https://github.com/user-attachments/assets/d712a985-b4f1-4bd6-b669-83f9b79c4502)

**Comment by sebastiankan** [comment]
Thanks for sharing @Tpow99 I have already done this, and I'm sure it's working as well on firebase_auth: 5.1.4 then stops working just by change firebase version to latest versions:
Working versions:
  firebase_analytics: 11.2.1
  firebase_app_check: 0.3.0+4
  firebase_auth: 5.1.4
  firebase_core: 3.3.0
  firebase_core_web: 2.17.4
  firebase_messaging: 15.0.4
  firebase_messaging_web: 3.8.12
  firebase_performance: ^0.10.0+4
  
  Not Working versions:
    firebase_analytics: 11.3.0
  firebase_app_check: 0.3.0+5
  firebase_auth: 5.2.0
  firebase_core: 3.4.0
  firebase_core_web: 2.17.5
  firebase_messaging: 15.1.0
  firebase_messaging_web: 3.8.13
  firebase_performance: ^0.10.0+5

**Comment by sebastiankan** [comment]
@SelaseKay I think this issue needs to be open till find out the problem, it's not for me I have reverted to last version and it's working for me, I just want to help to find the problem. Thanks in advance

**Comment by Tpow99** [comment]
@sebastiankan

After adding what I mentioned it is working for me with: 


  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  firebase_analytics: ^11.3.0
  cloud_firestore: ^5.3.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_remote_config: ^5.1.0
  firebase_app_check: ^0.3.1
  firebase_messaging: ^15.1.0

**Comment by Peng-Qian** [comment]
Same issue here. Please reopen the issue.

I suspect the problem lies in the communication between FMC and Apple’s remote background notification system within the package.

In my case, the iOS emulator works fine, and disabling push notifications allows me to trigger reCAPTCHA and send SMS verification codes on a real device.

Workaround: If anyone encounters the same problem, using a previous version can trigger reCAPTCHA and enable Phone Auth on real devices.

```dart
  firebase_auth: 5.1.4
  firebase_core: 3.3.0
```

**Comment by AnandSaran** [comment]
Hi i also facing same issue
Please reopen
