### ISSUE TITLE
Flutter firebase_messenging, not able to redirect specific detail screen when app is  killed in ios Working fine for android

### ISSUE THREAD

**Issue by bonisha-mandora** [firebase/flutterfire#16853]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

Recently faced this issue on our app.

Firebase push notifications works absolutely fine on Android and on ios as well in the background and foreground state. Proper detail screen redirection is doing tapping on push notifications.

But when the app is in the terminated state the notification shows up but the callback handler is not invoked in iOS only. In the Android detail screen redirection works fine even if the app is killed.

### Reproducing the issue

Keep your app in killed state, Send push notification to android and ios bith device token, Tapping on android app will open and redirect to proper detail screen, rather then in iOS App open but stay on home screen only do not redirect to exact detail screen based on id from notification payload.

### Firebase Core version

3.2.0

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment]
Hi @bonisha-mandora, it seems this issue has been resolved. Could you let us know which version of `firebase_messaging` you're currently using?
Here’s a similar issue for reference: https://github.com/firebase/flutterfire/issues/13442

**Comment by GeceGibi** [comment]
Same here. !

**Comment by GeceGibi** [comment]
The bug doesn’t necessarily occur when opening the app via a notification. Even when the app is manually launched after receiving a notification, the issue persists (assets fail to load. Exception: Image upload failed due to loss of GPU access).

Additionally, I tested it with an iPad (18.1.1) and various Android devices, and it works without any issues. The problem seems to be limited to iPhone devices only.

**Comment by Umeshkanase17** [comment]
I have the same issue in my case. The app redirects perfectly, but after 1 second, it automatically goes back, as if the app was terminated. Does anyone know the solution? Please let me know.
