### ISSUE TITLE
🐛 [firebase_auth] authStateChanges.listen sometimes doesn't works on the web

### ISSUE THREAD

**Issue by ekasetiawans** [firebase/flutterfire#4348]
## Bug report

**Describe the bug**
authStateChanges().listen sometimes not triggered when signed in or out.

### Steps to reproduce

1. add firebase_auth to pubspec.yaml
2. listen authStateChanges and catch user.
3. Run
4. signInWithEmailAndPassword
5. authStateChanges not triggered.

### Expected behavior

authStateChanges must be triggered just like on mobile.

---

## Additional context

This only happens on the web.
Sometimes we need to hot restart manually to make it works.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
ekasetiawans@MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on macOS 11.0.1 20B29 darwin-x64,
    locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (4 available)
    ! Error: iPhone 7 is busy: Processing cache files from device. Xcode will
      continue when iPhone 7 is finished. (code -10)

• No issues found!
ekasetiawans@MacBook-Pro ~ % 
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
ekasetiawans@MacBook-Pro retgoo_account_flutter % flutter pub deps -- --style=compact
Dart SDK 2.12.0-76.0.dev
Flutter SDK 1.25.0-4.0.pre
account_retgoo 1.0.0+1

dependencies:
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.1+1
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- intl 0.16.1 [path]
- provider 4.3.2+2 [flutter nested collection]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.3 [collection]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- clock 1.1.0-nullsafety.3
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.5
- fake_async 1.2.0-nullsafety.3 [clock collection]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.1+1 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.3-nullsafety.3
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.3
- plugin_platform_interface 1.0.2 [meta]
- quiver 2.1.3 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.5 [collection]
- vector_math 2.1.0-nullsafety.5
ekasetiawans@MacBook-Pro retgoo_account_flutter % 
```

</details>

---

**Comment by markusaksli-nc** [comment]
I'm seeing this as well on the latest master `1.25.0-5.0.pre.108` with 
```
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
```
```
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
```
<details>
  <summary>flutter doctor -v</summary>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
```
[√] Flutter (Channel master, 1.25.0-5.0.pre.108, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.25.0-5.0.pre.108 at C:\Development\flutter_master
    • Framework revision 995aa138cd (10 hours ago), 2020-12-08 09:18:02 +0530
    • Engine revision b0d31ae166
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.5981.155
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.55

• No issues found!
```
</details>
<details>
 <summary>Modified official code sample</summary>

```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter_signin_button/flutter_signin_button.dart';
import 'package:google_sign_in/google_sign_in.dart';

final FirebaseAuth _auth = FirebaseAuth.instance;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(AuthExampleApp());
}

/// The entry point of the application.
///
/// Returns a [MaterialApp].
class AuthExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Firebase Example App', theme: ThemeData.dark(), home: SignInPage());
  }
}

/// Entrypoint example for various sign-in flows with Firebase.
class SignInPage extends StatefulWidget {
  /// The page title.
  final String title = 'Anonymous number link test';

  @override
  State<StatefulWidget> createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  String uid = "";

  @override
  void initState() {
    changeUidText(_auth.currentUser);
    _auth.userChanges().listen(changeUidText);
    super.initState();
  }

  void changeUidText(User user) {
    setState(() {
      if (user == null) {
        uid = "Signed out";
        return;
      }
      uid = user.uid;
      if (user.email != null) {
        uid += " " + user.email;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          Builder(builder: (BuildContext context) {
            return FlatButton(
              child: const Text('Sign out'),
              textColor: Theme.of(context).buttonColor,
              onPressed: () async {
                final User user = await _auth.currentUser;
                if (user == null) {
                  Scaffold.of(context).showSnackBar(const SnackBar(
                    content: Text('No one has signed in.'),
                  ));
                  return;
                }
                _signOut();
                final String uid = user.uid;
                Scaffold.of(context).showSnackBar(SnackBar(
                  content: Text(uid + ' has successfully signed out.'),
                ));
              },
            );
          })
        ],
      ),
      body: Builder(builder: (BuildContext context) {
        return ListView(
          padding: EdgeInsets.all(8),
          scrollDirection: Axis.vertical,
          children: <Widget>[
            Text(uid),
            RaisedButton(
              child: const Text("Print currentUser info"),
              onPressed: () => print(_auth.currentUser.toString()),
            ),
            _EmailPasswordForm(),
          ],
        );
      }),
    );
  }

  // Example code for sign out.
  void _signOut() async {
    await _auth.signOut();
  }
}

class _EmailPasswordForm extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _EmailPasswordFormState();
}

class _EmailPasswordFormState extends State<_EmailPasswordForm> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Form(
        key: _formKey,
        child: Card(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Container(
                  child: const Text(
                    'Sign in with email and password',
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  alignment: Alignment.center,
                ),
                TextFormField(
                  controller: _emailController,
                  decoration: const InputDecoration(labelText: 'Email'),
                  validator: (String value) {
                    if (value.isEmpty) return 'Please enter some text';
                    return null;
                  },
                ),
                TextFormField(
                  controller: _passwordController,
                  decoration: const InputDecoration(labelText: 'Password'),
                  validator: (String value) {
                    if (value.isEmpty) return 'Please enter some text';
                    return null;
                  },
                  obscureText: true,
                ),
                Container(
                  padding: const EdgeInsets.only(top: 16.0),
                  alignment: Alignment.center,
                  child: SignInButton(
                    Buttons.Email,
                    text: "Sign In",
                    onPressed: () async {
                      if (_formKey.currentState.validate()) {
                        _signInWithEmailAndPassword();
                      }
                    },
                  ),
                ),
              ],
            ),
          ),
        ));
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  // Example code of how to sign in with email and password.
  void _signInWithEmailAndPassword() async {
    try {
      final User user = (await _auth.signInWithEmailAndPassword(
        email: _emailController.text,
        password: _passwordController.text,
      ))
          .user;

      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("${user.email} signed in"),
      ));
    } catch (e) {
      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("Failed to sign in with Email & Password"),
      ));
    }
  }
}
```
</details>

**Comment by Vinzent03** [comment]
In my case it only happens after a browser refresh. Before a refresh, sign in with a 'authStateChanges()' listener works fine.

**Comment by ekasetiawans** [comment]
an additional case, if the website has been published, you have to reload many times until it can capture data in authstatechanges.

**Comment by fourman-alex** [comment]
Additional info I can add is that it seems that the demo project, which doesn't explicitly use the published package `firebase_auth: ^0.18.4+1` and instead uses the github version with  
```
firebase_auth:
    path: ../
```
`authStateChanges` are fired correctly and as expected. 
In my case this is a definite regression as user persistance was working fine until lately users started noticing they have to login every time.

**Comment by fourman-alex** [comment]
I've looked more into this, mainly as this deeply impacts user experience, and I've found two configurations which work:
```
pubspec.yaml
-------------------
firebase_auth: 0.18.3
firebase_core: 0.5.2

index.html
-----------------
<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
```
OR
```
pubspec.yaml
-------------------
firebase_auth: 0.18.4+1
firebase_core: 0.5.3

index.html
-----------------
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-auth.js"></script>

```

So until this is fixed you can choose which functionality you rather sacrifice.

**Comment by aaahrens** [comment]
I want to note we've experience this issue in production as well.

**Comment by bernaferrari** [comment]
Probably same issue here. Need to clear the browser's cache and data every time, else it won't log-in.

**Comment by searchy2** [comment]
In terms of priority, I would like to see this issue categorized as high priority.

Because a user auth status listener is the ONLY reliable way Firebase Auth supports for fetching the authentication status of a user, without this working, everything auth related breaks.

I can provide a reproducible sample if that would help

**Comment by dkbast** [comment]
For me using auth.userChanges() was the (temporary) solution:

From firebase_auth.dart
```dart
  /// Notifies about changes to any user updates.
  ///
  /// This is a superset of both [authStateChanges] and [idTokenChanges]. It
  /// provides events on all user changes, such as when credentials are linked,
  /// unlinked and when updates to the user profile are made. The purpose of
  /// this Stream is to for listening to realtime updates to the user without
  /// manually having to call [reload] and then rehydrating changes to your
  /// application.
  Stream<User> userChanges() => _pipeStreamChanges(_delegate.userChanges());
```

**Comment by Sun3** [comment]
Any updates on this issue, I am also having the same problem. This is definitely a priority issue to fix.

Thanks.

**Comment by rlch** [comment]
I'm experiencing the same issue. Would love some clarity on if this is going to be fixed / if there's any workarounds for the time being, as it's affecting my users

**Comment by Zacherl** [comment]
For anyone struggling - I fixed it for myself like that:

`FirebaseAuth.instance
        .authStateChanges()
        .startWith(FirebaseAuth.instance.currentUser)`

**Comment by Ehesp** [comment]
This should be fixed in the latest version. Web & Native platforms have undergone a bit of a rework to keep them consistent with each other.

**Comment by russellwheatley** [comment]
Hey folks, is anyone still experiencing this issue after upgrading to the latest version?

**Comment by Merrit** [comment]
I just tried with version 2, my app still gets stuck on my splash screen waiting for an auth event.. for the time being I've worked around the issue by having the splash screen check if a user exists:

```dart
    WidgetsBinding.instance!.addPostFrameCallback((_) {
      final user = context.read<AuthenticationRepository>().currentUser;
      if (user == User.empty) {
        print('No user found on SpashPage');
      } else {
        Navigator.pushReplacementNamed(context, HomePage.id);
      }
    });
```

**Comment by searchy2** [comment]
The good news is that this issue seems to be resolved in production.
Unfortunately, hot reload still has this issue where #6192 is not resolved.

**Comment by Ehesp** [comment]
@searchy2 That's an issue with the Dart SDK, been fixed on `2.14.0-276.0.dev` - see https://github.com/dart-lang/sdk/commit/460887d8149748d3feaad857f1b13721faadeffa for more info.

**Comment by russellwheatley** [comment]
This issue, and the hot reload issue has now been resolved I believe.

**Comment by AlexKenbo** [comment]
> @searchy2 That's an issue with the Dart SDK, been fixed on `2.14.0-276.0.dev` - see [dart-lang/sdk@460887d](https://github.com/dart-lang/sdk/commit/460887d8149748d3feaad857f1b13721faadeffa) for more info.

No. 
When I turn on All exception - still appears...
