### ISSUE TITLE
🐛 [firebase_app_check] AppCheck prevents first Database call

### ISSUE THREAD

**Issue by kralle1987** [firebase/flutterfire#6862]
## Bug report

As soon as I add the Firebase App Check to my pubspec.yaml file, the first call to the Firebase Realtime Database does not work.
This happens every time I kill the app and restart it.

### Steps to reproduce

1. add firebase_app_check: ^0.0.2 to pubspec.yaml and click "Pub get" (no additional code required to reproduce)
2. create new child with databaseReference.child(someChild).set({});
3. check the Firebase console to see that no child is created in realtime database
4. 2nd, 3rd, 4th, .... creation attempts work fine
5. as soon as firebase_app_check: ^0.0.2 is removed from pubspec.yaml it works fine again

### Expected behavior

First call should be set as usual

### Sample project

pubspec.yaml:

dependencies:
...
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_database: ^7.1.2
  firebase_analytics: ^8.2.0
  firebase_app_check: ^0.0.2

Set Child:

    await databaseReference.child(someChild).set({
      'amount': 0,
      'result': 0,
      'total' : 0,
      'type': 'Avg',
      'private' : 'no',
      'passphrase' : '',
      'creator' : auth.currentUser.uid,
      'titlecrypt':encryptedTitle.base64,
      'descriptioncrypt':encryptedDescription.base64
    });

---

## Additional context

Firebase authentication is set to anonymous login.
Firebase Appcheck is not configured in the Firebase Console

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale de_DE.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.2)
[!] Android Studio
    ✗ android-studio-dir = /snap/android-studio/current/android-studio
    ✗ Android Studio not found at /snap/android-studio/current/android-studio
[✓] Android Studio
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
silium_flutter 1.1.3+16

dependencies:
- admob_flutter 1.0.1 [flutter meta]
- animated_button 0.2.0 [flutter]
- animation_wrappers 3.0.0 [flutter]
- cupertino_icons 1.0.3
- curved_navigation_bar 1.0.1 [flutter meta]
- easy_localization 3.0.0 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- expandable 5.0.1 [flutter]
- firebase_analytics 8.3.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_app_check 0.0.2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.0.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.5.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 7.2.0 [firebase_core flutter]
- firebase_remote_config 0.10.0+4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_balloon_slider 0.1.1 [flutter]
- flutter_countdown_timer 4.1.0 [flutter]
- flutter_easyloading 3.0.0 [flutter flutter_spinkit]
- flutter_staggered_animations 1.0.0 [flutter]
- intl 0.17.0 [clock path]
- package_info 2.0.2 [flutter]
- package_info_plus 1.0.5 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 1.2.0 [flutter]
- pull_to_refresh 2.0.0 [flutter]
- qr_code_scanner 0.4.0 [flutter]
- qr_flutter 4.0.0 [flutter qr]
- share_plus 2.1.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- simple_animations 3.1.1 [flutter supercharged pedantic]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqlite3 1.1.2 [collection ffi meta]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- unity_ads_plugin 0.2.3 [flutter]
- url_launcher 6.0.9 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.4 [crypto]
- vertical_barchart 2.0.0+2 [flutter]
- vibration 1.7.3 [flutter vibration_web]

dev dependencies:
- change_app_package_name 0.1.3
- flutter_launcher_icons 0.9.1 [args image path yaml]
- flutter_native_splash 1.2.1 [args image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters charcode clock collection crypto fake_async file matcher meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.2.0
- asn1lib 1.0.2
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- easy_logger 0.0.2 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_app_check_platform_interface 0.0.1+4 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.1+4 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.0.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.0.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 0.3.0+4 [firebase_core flutter meta plugin_platform_interface]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_spinkit 5.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.1.1 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.3 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.3 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_provider_linux 2.0.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.1 [meta]
- pointycastle 3.3.1 [collection convert js]
- process 4.2.1 [file path platform]
- qr 2.1.0 [meta]
- share_plus_linux 2.0.3 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.1 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- supercharged 2.0.0 [supercharged_dart flutter]
- supercharged_dart 2.0.0
- sync_http 0.3.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_linux 2.0.1 [flutter]
- url_launcher_macos 2.0.1 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.2 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.0
- vibration_web 1.6.2 [flutter flutter_web_plugins]
- vm_service 6.2.0
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by kralle1987** [comment]
might be the same as #6794

**Comment by markusaksli-nc** [comment]
Hi @kralle1987 
Are there any relevant errors or warnings logged?
Have you tried upgrading to the latest versions?
Thank you

**Comment by mikehardy** [comment]
What platform (ios or android) and real device or using Android emulator / iOS simulator, and using firebase database emulator or not?

On Android emulators (at least) using shared secrets (AppCheck debug token registered in firebase console), AppCheck + Database Emulator are currently not playing nicely together:

https://github.com/firebase/firebase-tools/issues/3663

But in other cases (android emulator against real database in cloud, or iOS simulator against firebase database emulator, or iOS against real database in cloud) we have success using AppCheck + database in sibling project react-native-firebase.

For Android emulator + firebase database emulator it does not work and we avoid it:

https://github.com/invertase/react-native-firebase/blob/f03589d6eed793b1f61b76d401401bf226799d26/tests/app.js#L46-L50

**Comment by kralle1987** [comment]
Updated to the latest versions, still the same.
No errors or warnings in Logcat.
The code just seems to stop there. 
Code after 

```
await databaseReference.child(someChild).set({
......
});
```
is also not executed.



Only tested it on Android. Same on real device and emulator.
Not using firebase database emulator.

Strangely, I really only need to add the line "firebase_app_check: ^0.0.2" to pubspec.yaml for it to happen. AppCheck is not configured on Client or Server side.

I also created a new firebase project in case there was something fishy, but still the same.

**Comment by mikehardy** [comment]
@maksymmalyhin  not sure if you've seen this one, but there may be something to the callable functions thing going on in database - there is definitely an issue in firebase-tools for the database emulator (issue linked above) but something else appears to manifest even without database emulator :thinking:

**Comment by maksymmalyhin** [comment]
@mikehardy Thank you for bringing this up. From the first glance it looks like a separate issue. I'll pass the issue to relevant teams. It also may be worth filing an issue in the [Android SDK repo](https://github.com/firebase/firebase-android-sdk) if you can reproduce it without Flutter in a native app.

**Comment by maksymmalyhin** [comment]
@mikehardy @kralle1987 Could you please check if the issue is reproducible in a native app with the native SDK with no Flutter involved? Then we will know where to look for the source of the issue first.

cc @rosalyntan @schmidt-sebastian

**Comment by mikehardy** [comment]
I won't have time (already chasing lots of other things down, sorry :sweat_smile: ) - but @kralle1987 if you've never done it before, the absolute fastest way is to clone this out and use it as the basis for a repro - it ends up being pretty quick in my experience - https://github.com/firebase/quickstart-android/tree/master/database (though unfortunately this is just a bit more involved because you have to do appcheck as well https://firebase.google.com/docs/app-check/android/safetynet-provider - there's no quickstart for it yet alas)

**Comment by kralle1987** [comment]
Luckily, I started off the app in Kotlin before switching to flutter.
So I have an app which does roughly the same.


My steps to reproduce:

1. created a new firebase project
2. added new google.service.json file
3. created a new realtime database in firebase
4. added implementation `'com.google.firebase:firebase-appcheck-safetynet:16.0.0-beta02'` to the build.gradle file
5. tested on emulator and physical device

Here also the exact same issue: first `set` does nothing, second, third, ... work fine.
No need to add `FirebaseAppCheck.getInstance()`.

Hope this helps!

**Comment by maksymmalyhin** [comment]
@kralle1987 Thank you! It's very helpful and it basically indicates that the issue most likely in the Android native SDK (or at least FireFlutter doesn't play too significant role here).

cc @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
I am able to reproduce this. Client logs:

```
2021-08-23 14:39:26.826 7170-7955/com.google.firebase.quickstart.database D/PersistentConnection: pc_0 - Sending app check.
2021-08-23 14:39:27.367 7170-7955/com.google.firebase.quickstart.database D/Connection: conn_1 - Sending data (contents hidden)
2021-08-23 14:39:27.368 7170-7955/com.google.firebase.quickstart.database D/WebSocket: ws_1 - Reset keepAlive. Remaining: 43602
2021-08-23 14:39:27.390 7170-7979/com.google.firebase.quickstart.database D/WebSocket: ws_1 - ws message: {"t":"d","d":{"r":4,"b":{"s":"invalid_token","d":"Could not parse token."}}}
2021-08-23 14:39:27.391 7170-7955/com.google.firebase.quickstart.database D/WebSocket: ws_1 - Reset keepAlive. Remaining: 44976
2021-08-23 14:39:27.392 7170-7955/com.google.firebase.quickstart.database D/WebSocket: ws_1 - HandleNewFrameCount: 1
2021-08-23 14:39:27.393 7170-7955/com.google.firebase.quickstart.database D/WebSocket: ws_1 - handleIncomingFrame complete frame: {t=d, d={r=4, b={d=Could not parse token., s=invalid_token}}}
2021-08-23 14:39:27.393 7170-7955/com.google.firebase.quickstart.database D/Connection: conn_1 - received data message: {r=4, b={d=Could not parse token., s=invalid_token}}
2021-08-23 14:39:27.393 7170-7955/com.google.firebase.quickstart.database D/PersistentConnection: pc_0 - App check failed: invalid_token (Could not parse token.)
```

The SDK sends a dummy token, but the backend rejects the token even though no enforcement is enabled. We will get this fixed.

Thanks for the report.

**Comment by PaulRudin** [comment]
I'm seeing this as well, and I also see that it's enough just to include firebase_app_check in pubspec.yaml, even if it's not imported anywhere.

**Comment by kralle1987** [comment]
Seems to be fixed in the latest update.
First call talked a bit longer (maybe 2 or 3 seconds) but it works now

**Comment by PaulRudin** [comment]
@kralle1987 - which version? I updated this morning and I'm still seeing this.

**Comment by kralle1987** [comment]
@PaulRudin 
It can be found in the official Firebase release notes: https://firebase.google.com/support/release-notes/android#2021-09-13

> Fixed an issue that prevented functions from proceeding after App Check failures.

I use the following Versions:

in pubspec.yaml:
`  firebase_core: ^1.6.0`
`firebase_database: ^8.0.0`
`firebase_app_check: ^0.0.2+1`

in build.gradle (app):
`implementation platform('com.google.firebase:firebase-bom:28.4.1')`

and in build.gradle (android):
`classpath 'com.google.gms:google-services:4.3.10'`

I cleared the app data on the device and did a Flutter Clean to make sure everything is fine.

**Comment by PaulRudin** [comment]
Interesting, thanks for setting that all out. However even when ensure I have all the same versions I see the same thing. I notice that the fix you quote mentions functions. The issue I'm experiencing, and the original bug report, is to do with the realtime database; and not firebase functions.

**Comment by mikehardy** [comment]
@PaulRudin the link to android release notes is for the whole release, there's a note about database just under functions, it is in the release and I believe the issue should be resolved. I'd re-examine local environment (project build caches, versions, etc) to make sure all the new shiny stuff is truly included, it really should be working now 🤔

**Comment by PaulRudin** [comment]
Hmm - OK, I'll keep digging. 
(Incidentally - the fix mention for realtime says "issue writes", although in my case it hangs at the first read.)

**Comment by PaulRudin** [comment]
I've killed the gradle daemon, deleted the gradle cache, updated everything I can in pubspec.yaml, run flutter clean, and I still see the same thing.  I don't know what else to try.

**Comment by PaulRudin** [comment]
Right, but I thought that the situation was supposed to be that the client side code ignored the server side errors, so it should be possible to use it with the emulator? 

I have no problems with the a real live database with app check enabled... but against the emulator or a real database without appcheck the issue arises.

(And as mentioned in the original report - it's enough just to include appcheck in pubspec.yaml, even if it's not imported anywhere in my flutter code.)

**Comment by mikehardy** [comment]
Hmm - we may have slightly different test configs / failure modes. Your mention of "a real database without appcheck" is a case that I'm not probing in react-native-firebase at least so I'm not sure where along the set of things-in-play that breaks down.

The rest of your statements "...that the client side code ignored the server side errors" - I'm not sure that assertion holds so conclusions based on it are unknown, for me and "it's enough just to include appcheck" - it's my understanding that the native parts do initialization on app startup and register with each other, so simply including it is enough to change quite a bit of behavior in the native SDK, whether you then use it or not

**Comment by PaulRudin** [comment]
The original bug report was for usage against a real database without appcheck enabled: "Firebase Appcheck is not configured in the Firebase Console".

It certainly possible that "... the client side code ignored the server side errors" is in fact false (since that's what this bug report is highlighting), but I was under the impression that that was the intention, precisely so that we were able to use code with appcheck in these situations. 

It surely can't be the intention that we edit pubspec.yaml to remove appcheck if we want to use our application code with the emulator, and then put it back in other circumstances?

ISTM that the situation is that the bug report is identifying a real problem, and to date the problem still exists? No?

It may be that the problem is basically in the firebase native android stuff, so not really something that can be fixed the flutter specific code - I dunno.

**Comment by mikehardy** [comment]
To set everything I understand out, I can only say I think I know these things:

In the case where App Check is included in an android client build, and generates invalid tokens, and RTDB is not set to be App Check protected, and real RTDB is used, this is supposedly fixed with firebase-android-sdk 28.4.0+, but you do not reproduce success @PaulRudin, correct?

In this case, if valid App Check tokens are generated, it should work and has for me for quite a few firebase-android-sdk versions.

This is a case I test multiple times a day (via react-native-firebase CI and local development)

In the case where App Check is included in a client, and generates valid or invalid tokens, and RTDB is not set to be App Check protected, and RTDB emulator is used, this is not working for android currently based on a firebase-tools issue linked above.

This is a case I test much less frequently but has consistent results, and requires me to detect platform in E2E tests for react-native-firebase and avoid the RTDB emulator for android currently.

**Comment by weixifan** [comment]
Filed an internal bug b/211315540 to track.

**Comment by weixifan** [comment]
> Hey folks, is anyone able to confirm if this is still an issue, please? It appears, at least, that a fix was merged some time ago [firebase/firebase-android-sdk#2928](https://github.com/firebase/firebase-android-sdk/pull/2928)

Apologies for the delayed response -- yes, that PR should indeed fix this issue. I'm going to leave this issue as-is for now in case the OP has further issues related to this change.

**Comment by mikehardy** [comment]
I no longer have AppCheck + RTDB issues on either cloud database or emulator. I think this is resolved.
