### ISSUE TITLE
🐛 [firebase_crashlytics]-[macOS] 'ExceptionModel_Platform.h' file not found

### ISSUE THREAD

**Issue by mrrhak** [firebase/flutterfire#8562]
## Bug report

**Describe the bug**
fatal error: 'ExceptionModel_Platform.h' file not found

---

### Error log

```
/Users/mrrhak/Documents/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.7.1/macos/Classes/FLTFirebaseCrashlyticsPlugin.m:7:9: fatal error: 'ExceptionModel_Platform.h' file not found
#import "ExceptionModel_Platform.h"

1 error generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
** BUILD FAILED **

Exception: Build process failed
Exited (sigterm)
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on Mac OS X 10.15.7 19H1824 darwin-x64, locale en-KH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
mrrhak@iMacs-iMac m68_graphql_client % flutter pub deps -- --style=compact
Dart SDK 2.16.2
Flutter SDK 2.10.5
m68_graphql_client 1.0.0

dependencies:
- ferry 0.10.5-dev.3 [gql rxdart gql_link gql_exec meta collection hive built_value ferry_exec normalize ferry_cache]
- ferry_hive_store 0.4.5-dev.1 [hive ferry_store rxdart collection]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- gql_http_link 0.4.2 [gql gql_exec gql_link http http_parser meta]

dev dependencies:
- build_runner 2.1.10 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- ferry_generator 0.5.0-dev.10 [gql gql_code_builder built_collection code_builder build path ferry_exec yaml dart_style glob built_value_generator built_value analyzer]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- built_value_generator 8.1.4 [analyzer build build_config built_collection built_value source_gen quiver]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.1.1 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ferry_cache 0.5.5-dev.10 [ferry_exec meta rxdart normalize ferry_store collection pedantic]
- ferry_exec 0.1.5-dev.2 [gql gql_exec gql_link meta async collection built_collection built_value]
- ferry_store 0.4.4 [rxdart collection]
- file 6.1.2 [meta path]
- fixnum 1.0.0
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- gql 0.13.1-alpha+1645425888336 [collection meta source_span]
- gql_code_builder 0.5.0 [analyzer built_collection built_value code_builder collection gql gql_exec path]
- gql_exec 0.4.0 [collection gql meta]
- gql_link 0.4.2 [gql gql_exec meta]
- graphs 2.1.0 [collection]
- hive 2.0.6 [meta crypto]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.4.0 [meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- normalize 0.6.0+1 [gql collection]
- package_config 2.0.2 [path]
- path 1.8.0
- pedantic 1.11.1
- pool 1.5.0 [async stack_trace]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- rxdart 0.27.3
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.3 [analyzer async build dart_style glob meta path pedantic source_span yaml]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by mono0926** [comment]
That seems to have been broken since 2.7.0.
It is not a problem in [2.6.3](https://pub.dev/packages/firebase_crashlytics/changelog#263).

**Comment by darshankawar** [comment]
Thanks for the updates. Observed the same on plugin's official repo as well.

<img width="781" alt="Screenshot 2022-05-03 at 4 20 21 PM" src="https://user-images.githubusercontent.com/67046386/166440988-082017c4-603d-4e2c-907c-1761d2e3e566.png">


<img width="808" alt="Screenshot 2022-05-03 at 4 20 42 PM" src="https://user-images.githubusercontent.com/67046386/166440999-df91a471-2d2c-4357-a551-f65ce777c1b4.png">

/cc @russellwheatley

**Comment by dhirajhimani** [comment]
I am still able to reproduce this 
my pubspec.yaml for flutterfire
`
  firebase_analytics: ^9.1.7
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_crashlytics: ^2.7.2
`

flutter --version 

Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (2 weeks ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

**Comment by mono0926** [comment]
> I am still able to reproduce this
my pubspec.yaml for flutterfire
firebase_analytics: ^9.1.7 firebase_auth: ^3.3.17 firebase_core: ^1.16.0 firebase_crashlytics: ^2.7.2

It appears that this fix was merged but just not included in 2.7.2.

**Comment by jonbhanson** [comment]
I also had this problem with 2.7.2. I was able to resolve by copying the missing file from the ios folder:

```
cp ~/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.7.2/ios/Classes/ExceptionModel_Platform.h ~/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.7.2/macos/Classes/
```
Adjust path according to the location of your flutter install.  Thanks @xPutnikx for the suggestion.

**Comment by praveentcom** [comment]
This is not fixed. Reproducible with Flutter 3.0.0, firebase_crashlytics 2.7.2.

**Comment by mrrhak** [comment]
I see this problem is fixed and merged [here](https://github.com/firebase/flutterfire/pull/8570/commits/1d7fffc7efa9d680e1f8d6e48f0a77e1bd7a9cb0) but they not yet make new release version to `pub.dev` . So you can downgrade to version `firebase_crashlytics: ^2.6.3` and waiting for a new release.

**Comment by russellwheatley** [comment]
This is now fixed. Thanks.
