### ISSUE TITLE
Release & Debug version of the app asking keychain permissions 

### ISSUE THREAD

**Issue by ollydixon** [firebase/flutterfire#8811]
Related to https://github.com/firebase/firebase-ios-sdk/issues/5540

When launching the app customers are reporting that they are asking for sensitive key-chain access.

We had to include Firebase Core in order to get FCM working..

Anyway around this? It's not acceptable to ask 8 times for Keychain access everytime the customer launches and many refuse to use "Always allow" which is completely reasonable.

**Comment by ollydixon** [comment]
@paulb777 disabling the library stops with ```Platform.isMac``` stops it asking for keychain access.

**Comment by paulb777** [comment]
One more thought since the issue sounds similar to a development-only workflow we've seen for macOS.  How is the app distributed? We would expect App Store signing to obviate the need for any keychain permission popups.

**Comment by darshankawar** [comment]
@ollydixon 
If I understand correctly, the keychain permission is being asked for macOS after adding firebase_core / firebase_messaging plugin ?

**Comment by ollydixon** [comment]
@darshankawar indeed. Multiple times on every launch. Something that is no acceptable for a user journey.

**Comment by ollydixon** [comment]
@darshankawar sorry for the delay. We removed firebase in this project and are using an alternative push notifications system because of this bug. 

I’m sure the sample app will give the same bug for MacOS :-)

**Comment by maheshmnj** [comment]
@ollydixon Incase you have more info for us regarding how to reproduce the issue, feel free to write back.

**Comment by ollydixon** [comment]
@maheshmnj I've given enough info for you to replicate. Just use the sample app and run it in MacOS.

**Comment by maheshmnj** [comment]
@ollydixon 

I ran the release version of flutter counter app targeting macOS with the following dependencies

```
 firebase_core: ^1.17.1
 firebase_messaging: ^11.4.1
```

<details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutter run -d macos --release
Launching lib/main.dart on macOS in release mode...
Running pod install...                                           1,332ms
objc[16507]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1e4faf640) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1086802c8). One of the two will be used. Which one is undefined.
objc[16507]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1e4faf690) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108680318). One of the two will be used. Which one is undefined.
objc[16507]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1e4faf458) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1086804f8). One of the two will be used. Which one is undefined.
objc[16507]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e4faf4a8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108680548). One of the two will be used. Which one is undefined.
objc[16507]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e4faf4f8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108680598). One of the two will be used. Which one is undefined.
objc[16507]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1e4faf548) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1086805e8). One of the two will be used. Which one is undefined.
objc[16507]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1e4faf598) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108680638). One of the two will be used. Which one is undefined.
objc[16507]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1e4faf5e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108680688). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-0019553C36F2001E }
{ platform:macOS, arch:x86_64, id:00008103-0019553C36F2001E }
Building macOS application...                                           

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
2022-06-13 10:40:16.870 sample[17552:136674] The operation couldn’t be completed. (OSStatus error 13.)
```
</details> 

But I don't see app asking for keychain permissions.
Let me know if I am missing anything.

Thanks

**Comment by ollydixon** [comment]
@maheshmnj was their an update?

Anyhow, you have probably previously accepted all. It remembers forever. Go to the keychain and clear any references to Google, flutter (there’s many other names but I can’t remember).

I was getting this permission on two laptops and the QA personelle are reporting it as a bug.

**Comment by ollydixon** [comment]
@maheshmnj You need to connect to the Firebase service (your own) to fully run the test as you have not even initialized the package it will do nothing. 

```
await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
```

^^ Will trigger the keychain requests on MacOS.

**Comment by maheshmnj** [comment]
Thanks for the info @ollydixon, I ran the below cloud_firestore  sample code in release mode targeting macOS, And I was able to reproduce the issue, The keychain permission prompts were shown at least 7-8 times. 


https://user-images.githubusercontent.com/31410839/173536225-494aa506-a933-49c2-a7da-c8489da47e9c.mp4

I am quite not sure if this from flutter, firebase plugins/sdk , Labeling this issue for further insights from the team.


<details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 cloud_firestore_example % flutter run -d macos --release
Launching lib/main.dart on macOS in release mode...
Running pod install...                                             12.7s
objc[98739]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1fd99f640) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1082802c8). One of the two will be used. Which one is undefined.
objc[98739]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1fd99f690) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108280318). One of the two will be used. Which one is undefined.
objc[98739]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1fd99f458) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1082804f8). One of the two will be used. Which one is undefined.
objc[98739]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1fd99f4a8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108280548). One of the two will be used. Which one is undefined.
objc[98739]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1fd99f4f8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108280598). One of the two will be used. Which one is undefined.
objc[98739]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1fd99f548) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1082805e8). One of the two will be used. Which one is undefined.
objc[98739]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1fd99f598) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108280638). One of the two will be used. Which one is undefined.
objc[98739]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1fd99f5e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108280688). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-0019553C36F2001E }
{ platform:macOS, arch:x86_64, id:00008103-0019553C36F2001E }
/Users/mahesh/Desktop/triage-examples/flutterfire_examples/cloud_firestore_example/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 12.2. (in target 'leveldb-library' from project 'Pods')
Building macOS application...                                           

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
2022-06-14 14:16:20.683 cloud_firestore_example[7449:457108] The operation couldn’t be completed. (OSStatus error 13.)


```
</details> 

<details>
<summary>code sample</summary>

```dart
// Copyright 2020, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:math';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

/// Requires that a Firestore emulator is running locally.
/// See https://firebase.flutter.dev/docs/firestore/usage#emulator-usage
bool USE_FIRESTORE_EMULATOR = false;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  if (USE_FIRESTORE_EMULATOR) {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }
  runApp(MyApp());
}

final messagesCollection = FirebaseFirestore.instance.collection('messages');

class MessagesList extends StatefulWidget {
  const MessagesList({Key? key}) : super(key: key);

  @override
  _MessagesListState createState() => _MessagesListState();
}

class _MessagesListState extends State<MessagesList> {
  @override
  Widget build(BuildContext context) {
    final query =
        messagesCollection.where('message', isEqualTo: 'Hello World').orderBy(
              'sentDateTime',
              descending: true,
            );
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final minutes = Random().nextInt(60);
          final DateTime dateTime =
              DateTime.now().add(Duration(minutes: minutes));
          messagesCollection.add({
            'message': 'Hello World',
            'sentDateTime': Timestamp.fromDate(dateTime)
          });
        },
        child: Icon(Icons.add),
      ),
      appBar: AppBar(
        title: const Text('Firestore Messages'),
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: query.snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(
              child: Text(snapshot.error.toString()),
            );
          }

          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final data = snapshot.data!.docs;

          return ListView.builder(
            itemCount: data.length,
            itemBuilder: (context, index) {
              final dateTime =
                  (data[index]['sentDateTime'] as Timestamp).toDate();
              return ListTile(
                title: Text('${data[index]['message']}'),
                trailing: Text(dateTime.toString()),
              );
            },
          );
        },
      ),
    );
  }
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MessagesList(),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by ollydixon** [comment]
@maheshmnj awesome now you see the bug. It's also the same for release mode. We cannot use Firebase on MacOS because of this, not customer is going to accept a high suspicious key-chain request 8 times.

**Comment by Aksi0** [comment]
I have the same trouble. The first launch of the application without trying keychain. Everyone else with a bunch of keychain queries. Only core and analytics installed.

**Comment by Aksi0** [comment]
The error was fixed after configuring the application signature via xcode.

**Comment by tommienu** [comment]
> The error was fixed after configuring the application signing via xcode.

Can you elaborate a bit on this please?

**Comment by ollydixon** [comment]
@Aksi0 yes Aksi0, because we are signing a release version via the store. So I don't think this is a fix.

**Comment by tommienu** [comment]
Problem reproduced when using crashalytics (so it's not only plugin:analytics), the error is probably in plugin:core.

* Throw Exception() in initState()
* Keychain access is triggered with crashalytics is sending the error to the FB backends.

**Comment by ollydixon** [comment]
@tommienu we're not using ```crashalytics``` fyi, just Firebase messaging.

**Comment by tommienu** [comment]
> @tommienu we're not using `crashalytics` fyi, just Firebase messaging.

Even more indication that the error is somewhere plugin:core then.

**Comment by ollydixon** [comment]
@tommienu indeed, this library, not good that they are forcing us to use this library to do Push Notifications on Android (because we had the nice and simple GCM). Otherwise I'd never put Firebase into any of our projects. Ah well.

**Comment by GroovinChip** [comment]
I am having this issue with macOS as well - every time my app is run, in both debug and release modes, I am prompted for keychain access, and as mentioned above, this is not acceptable behavior for a user journey. In fact, this issue is actively preventing me from being able to release an app I've been working on.

I have tried the following things to fix the issue, with no success:
* Changing app signing from "Sign to run locally" to "Development" (this causes the app to crash after allowing keychain access)
* Turning off app sandbox (this actually breaks the app completely - it doesn't crash, but it also doesn't work)

If anyone has any insight into fixing this issue, it would be appreciated. Again, this is a release-blocking bug and unacceptable UX.

**Comment by maheshmnj** [comment]
The irony of this bug I can reproduce this in my own project

**Comment by ollydixon** [comment]
Honestly I know this isn't productive. But Firebase iOS libraries have been a bane for so many years. Even in the React Native days they were plagued with build issues and crashes.

I made a suggestion that perhaps the Flutterfire team write the whole library in Dart and not use the native libraries.

**Comment by tommienu** [comment]
Any chance we can get this into triage? Especially since this blocks any firebase release on macOS.

I'll spend some time this weekend trying older versions for this library to see if this is a recent regression. And if so, in which version it's introduced.

**Comment by russellwheatley** [comment]
I've just ran the Firebase Messaging example & the Cloud Firestore example and I didn't get the keychain access request in either instance. Out of curiosity, could the users who are experiencing this issue let me know if you are initializing your app from dart code or do you have the `GoogleService-Info.plist` in your Runner directory? 

If you wish to add the service file easily, run `flutterfire configure` (use latest version of FlutterFire CLI) in the root of your app and it should write the service file into your macOS Runner directory.

**Comment by ollydixon** [comment]
@russellwheatley used the CLI.

**Comment by tommienu** [comment]
> Out of curiosity, could the users who are experiencing this issue let me know if you are initializing your app from dart code or do you have the `GoogleService-Info.plist` in your Runner directory?

We might be on to something here. I'm actually able to run the app without any error by doing the following:
* Remove all `GoogleService-Info.plist` files from my projects (i accidentally had one in /macos as well)
* Compile and run the app, ensure that it fails with the `GoogleService-Info.plist`-file missing error.
* Run `flutterfire configure` and let it create the `GoogleService-Info.plist`-file.

I'm now able to run the app without the aforementioned errors. I'll send this build to a few testers to confirm that it solves the problem.

My guess is that I might have been doing 50% old style setup (downloading the `GoogleService-Info.plist` file manually) and then running the new style setup (`flutterfire configure`). Or the other way around.

**Comment by russellwheatley** [comment]
@tommienu have you tried creating a new app on the Firebase Console, updating the bundle id in Xcode and writing the service file again? I just [noticed this](https://stackoverflow.com/a/71899019/5681607) and wonder whether there is something to it 🤔 

> I don't get the error if I change the version parameter back to the previous value in pubspec.yaml.

Do you mean changing the version of the app?

**Comment by ollydixon** [comment]
We used the CLI as I mentioned before, we created 2 files one for DEV and one for PROD for real time switching. PROD is default.

This doesn't work for Android, you need to restart the app and have the service file, so that's broken but off topic for this iOS issue.

Just checking here, you are testing with MacOS right and not iOS? The bug is related to MacOS.

**Comment by russellwheatley** [comment]
Yes, macOS. My response was to @tommienu.

**Comment by tommienu** [comment]
> @tommienu have you tried creating a new app on the Firebase Console, updating the bundle id in Xcode and writing the service file again? I just [noticed this](https://stackoverflow.com/a/71899019/5681607) and wonder whether there is something to it 🤔

I didn't try this, but I did the full renaming of the app, including SKU, new distribution cert and BUNDLE_ID. And that didn't work.

I'll try and create a new Firebase project from the `flutterfire`-tool and see if this solves the issue. 

> > I don't get the error if I change the version parameter back to the previous value in pubspec.yaml.
> 
> Do you mean changing the version of the app?

Yes, correct.

**Comment by tommienu** [comment]
> > @tommienu have you tried creating a new app on the Firebase Console, updating the bundle id in Xcode and writing the service file again? I just [noticed this](https://stackoverflow.com/a/71899019/5681607) and wonder whether there is something to it 🤔
> 
> I didn't try this, but I did the full renaming of the app, including SKU, new distribution cert and BUNDLE_ID. And that didn't work.
> 
> I'll try and create a new Firebase project from the `flutterfire`-tool and see if this solves the issue.

The same issue, unfortunately. 

* I removed all keys from the keystore (to avoid collisions)
* Deleted `GoogleService-Info.plist` from `Runner`-folder.
* Ran `flutter clean`
* Ran `flutterfire configure` and created a new Firebase project for MacOS via the command line tool.
* Ran the app, first run ran fine (since it wrote the initial keys to the keystore)
* Subsequent runs caused the keystore-access errors.

**Comment by TammiLion** [comment]
> Out of curiosity, could the users who are experiencing this issue let me know if you are initializing your app from dart code or do you have the GoogleService-Info.plist in your Runner directory?`

In our project we have the GoogleService-Info.plist in the Runner directory and unfortunately experience the same issue.

@russellwheatley did you add/try the step @ollydixon mentioned after @maheshmnj first couldn't reproduce it using the sample project either? once he did those steps he was able to reproduce the issue so maybe the same works for you too (added a screenshot of the specific comments)
![Schermafbeelding 2022-08-16 om 17 10 07](https://user-images.githubusercontent.com/2879338/184914685-103e1205-1b64-4d75-ae2c-b9a7e4073ab8.png)

**Comment by russellwheatley** [comment]
Hey folks, I've spent a couple of hours this morning trying to reproduce this on a fresh app install. I installed `firebase_core`,  `firebase_analytics` & `firebase_crashlytics` and updated the `main.dart` like the below:

<details>
<summary>code sample</summary>
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';

void main() async {
  runZonedGuarded<Future<void>>(() async {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;

    runApp(const MyApp());
  }, (error, stack) => FirebaseCrashlytics.instance.recordError(error, stack));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }
  
  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(onPressed: (){
              FirebaseCrashlytics.instance.crash();
            }, child: const Text('press me'),),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```
</details>

I've also updated the version ran in debug and release mode and I still couldn't get a keychain access prompt.

Interestingly, when I ran this command:

```bash
flutter create mac_keychain_repro
```

I noticed this "signing iOS app" log:
```bash
Signing iOS app for device deployment using developer identity: "Apple Development: Michael Diarmid (88BU8MA94Y)"
Creating project mac_keychain_repro...
Running "flutter pub get" in mac_keychain_repro...
```

At this point, I'm not spending anymore time trying to reproduce. If you can create a repro for me, I will happily look into it. I currently suspect a configuration issue and would advise ensuring you've fully complied with the macOS [documentation](https://docs.flutter.dev/deployment/macos) for Flutter.

**Comment by TammiLion** [comment]
@russellwheatley just to be sure, did you also create a firebase project in firebase and set it up in the project?

**Comment by russellwheatley** [comment]
I used an existing firebase project but it created a new macOS app on the project.

**Comment by TammiLion** [comment]
Ok cool, then I would indeed expect that you would also see these keychain prompts, from what I can see comparing our GoogleService-Info plist files, the iOS and MacOS ones have different values for the GOOGLE_APP_ID and one of the prompts is always for the "idvalue;*". I will make a repo with a sample project then, maybe then you can spot what is different/ gone wrong and hopefully with that project you will be able to reproduce the problem.

**Comment by russellwheatley** [comment]
@TammiLion Appreciated  🙏

**Comment by TammiLion** [comment]
Made a sample project and managed to reproduce it. Some (for me easily overlooked steps). In Xcode setting the signing to your own signing (so not Sign to run Locally). Adding the Firebase.configure() into the AppDelegate.swift (if this is wrong please let me know). In our project we use Firebase Crashlytics and Firebase Messaging and I saw the same for @maheshmnj so I also added it in the pubspec. I made a video of the entire process but the interesting stuff only happens at the end of the video (besides uploading the repo to git :p).

https://github.com/TammiLion/macos_keychain_firebase_attempt2

Here is the google drive link to the 40+ min video. https://drive.google.com/file/d/13G3FWqlz3r_FwbfoBciJQCILqvxzozf1/view?usp=sharing
(Google drive is processing it, so it might not be available immediately)
The "interesting" stuff start around the 33 minute mark. This is the point where I realize I also can't reproduce it immediately just from a sample project. I then open the XCode workspace of the project in which I can reproduce it and start adding the Firebase.configure() to the AppDelegate.swift.

**Comment by russellwheatley** [comment]
@TammiLion Thank you for sharing your setup. The video is only 26 seconds long, but I didn't need to watch it anyway. 

You do not need to add `FirebaseApp.configure()` to your AppDelegate. The `firebase_core` plugin already takes care of configuration [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.m#L47).

@tommienu did you also add `FirebaseApp.configure()` to your AppDelegate?

**Comment by tommienu** [comment]
> @tommienu did you also add `FirebaseApp.configure()` to your AppDelegate?

Nope, here's my AppDelegate.swift:

```
import Cocoa

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    NSApp.setActivationPolicy(.accessory)
    return false
  }
}
```

I believe I've configured this according to the documentation.

**Comment by tommienu** [comment]
FWIFW, this sounds like a regression from this [old issue](https://github.com/firebase/firebase-ios-sdk/issues/5540) from 2020. Which was fixed in Firebase release 6.26.0, according to this [comment]( https://github.com/firebase/firebase-ios-sdk/issues/5540#issuecomment-654279937).

Understanding what changed there might assist with understanding why it's now resurfacing.

**Comment by GroovinChip** [comment]
Folks, I have been following this conversation closely over the last few days and I'm super confused as to whether there is a resolution for this issue or not. @russellwheatley seems to feel that this is a user configuration issue, yet @TammiLion is able to reproduce the issue, and @tommienu thinks there is a regression. Do we know what's going on here yet or is this still an ongoing investigation?

**Comment by TammiLion** [comment]
@russellwheatley thanks for the answer. I removed the Firebase.configure() from the AppDelegate.swift in the sample project. Unfortunately the problem still occurs.

Here's the actual video (once again, might not be immediately available due to drive processing it, will also edit the old comment): https://drive.google.com/file/d/1oXZEAc0U7abGL2Fe1ygDUPUXf-WOFVBL/view?usp=sharing

**Comment by ncooke3** [comment]
Hi everyone, 

Apologies for the trouble here and thank you for all the useful information. The [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk) team is aware of the issue and we have been actively working on a fix to resolve this. This issue has popped up in a few GitHub issues so I'm going to centralize communications in [firebase-ios-sdk/#9392](https://github.com/firebase/firebase-ios-sdk/issues/9392), but I will also update this thread when I have a more substantial update. 

I will share another update soon!

**Comment by ncooke3** [comment]
Hi everyone, I have an update [here](https://github.com/firebase/firebase-ios-sdk/issues/9392#issuecomment-1238751984). 

We have a fix that is currently planned for release in Firebase 9.6.0 next week. Thanks!

**Comment by ncooke3** [comment]
Hi everyone, 

Just a quick fyi that Firebase 9.6.0 has been released. This release should unblock this issue @darshankawar.

Please continue the conversation here or in [firebase-ios-sdk/#9392](https://github.com/firebase/firebase-ios-sdk/issues/9392) if the issue persists. 

As noted in [this comment](https://github.com/firebase/firebase-ios-sdk/issues/9392#issuecomment-1238751984) and in the [release notes](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore/CHANGELOG.md#firebase-960), please enable the Keychain Sharing capability for your macOS targets to make sure everything works properly.

Thanks!

**Comment by darshankawar** [comment]
@ollydixon Please check above comment and re-verify to confirm.

**Comment by ollydixon** [comment]
@ncooke3 do customers need to enable keychain sharing for their apps? As that won’t be an option.

Also; what is the reason for us enabling it? I don’t see the point.

**Comment by ncooke3** [comment]
Hi @ollydixon 

Thank you for the questions. I have answered each one below.

> do customers need to enable keychain sharing for their apps?

1. A developer building a Mac app using Firebase needs to do two things to **ensure their app’s users do not see keychain access prompts**:
    - Use a Firebase version equal or greater than 9.6.0
    - Add the Keychain Sharing capability to the provisioning profile they use to sign their app

> I don’t see other MacOS apps requesting this; and if they do I reject.

2. I understand your concern. It is likely the case that such Mac apps either do not access the keychain or use the solution introduced in Firebase 9.6.0.

> Apple will reject our apps without valid reason for keychain access.

3. There _is_ a reason that the Keychain Sharing capability needs to be added. Firebase uses the keychain to store SDK data. For example, [Firebase Installations](https://firebase.google.com/docs/projects/manage-installations) is an
SDK that is depended on by other [Firebase products](https://firebase.google.com/docs/projects/manage-installations). Firebase Installations manages _Installation IDs_, which map to an installed instance of a Firebase app. The implementation of this SDK is shared across platforms. At the time of its implementation, the Keychain was chosen to store these unique identifiers.

> What is the reason for us enabling it? I don’t see the point and it’s not explained. Non of our apps ‘SDKs’ use the keychain ..

4. Please refer to these places for additional documentation regarding this issue:
    - [Firebase 9.6.0 release notes](https://firebase.google.com/support/release-notes/ios#version_960_-_september_13_2022) 
    - [Firebase for Apple Platforms FAQ](https://firebase.google.com/docs/ios/troubleshooting-faq#macos-keychain-sharing)
    - Additionally, I posted [this](https://github.com/firebase/firebase-ios-sdk/issues/9392#issuecomment-1238751984) post to give an explanation as to why it should be enabled. Apologies for not posting it here; I posted it in [firebase-ios-sdk/#9392](https://github.com/firebase/firebase-ios-sdk/issues/9392). I'm using [firebase-ios-sdk/#9392](https://github.com/firebase/firebase-ios-sdk/issues/9392) as the central channel to track this issue and reduce cross-posting. 

     Additionally, the Firebase team is planning on moving away from using the keychain as a storage container where possible. It will take some work to do this, so it would be targeted for a future Firebase 10.x.0 release. For now, the fix in Firebase 9.6.0 will unblock your Mac app(s) from prompting users for permission to access the keychain. All you need to do is upgrade and add the Keychain Sharing capability to the provisioning profile you use to sign your Mac app(s).

> Apple provides a very simple push notifications service/key like on iOS; why is Firebase not utilizing this? 

5. I understand, but custom solutions are sometimes needed to reach the desired functionality. And for what it's worth, [Firebase Messaging does make use of APNs](https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_authentication_key).

> Why is it using the keychain in the first place?

6. Please refer to answer 4.

Please let me know if you have further questions.

**Comment by ollydixon** [comment]
@ncooke3 

Thanks for the info.

> There is a reason that the keychain Sharing capability needs to be added. Firebase uses the keychain to store SDK data. For 

Why not use library folder/cache or app folder for this. Storing it inside the key-chain seems a bit strange? You're asking us expose sensitive data, our key-chains might contain passwords and other items that we don't want to expose to any SDK's inside out app.

> Apple will reject our apps without valid reason for keychain access.

If we get an awkward reviewer which sometimes happens, we still have no reason to use the keychain. Our answer can't be 'cause some SDK inside our app uses it; they won't accept that.

**Comment by ncooke3** [comment]
> Why not use library folder/cache or app folder for this. 

Firebase uses the keychain to store various bits of SDK data. For example, Firebase Auth allows you to manage user accounts. Account information is a good example of something that the Keychain is designed to store. Storing such information in the keychain is done to _protect_ such information.

When SDKs are designed, a storage solution is chosen based on the requirements at that time. That said, we are working on reviewing our use of the Keychain, and if we find that the Keychain's security is not needed, then we will migrate away as necessary. We will be working on this and any resulting changes can be expected in a Firebase 10.X.0 release.

> Storing it inside the key-chain seems a bit strange?

The [Keychain](https://developer.apple.com/documentation/security/keychain_services) can store all sorts of data. And it has its own trade-offs just like any other storage solution (File System, User Defaults, database, etc.). 

While I was not involved in its design, I believe Firebase Installation tokens were stored in the keychain rather than an unprotected storage container out of an abundance of caution. And as I said in my previous answer, it's worth us examining whether or not the SDK needs to be that defensive. From an implementation and testability perspective, the Keychain can be difficult to deal with because of its API surface. So there are multiple benefits to not using the Keychain (as long as the data does not pose a risk by being stored in an unsecure container).

> You're asking us expose sensitive data, our key-chains might contain passwords and other items that we don't want to expose to any SDK's inside our app.

Nobody is asking that. Just because an SDK uses the keychain does not mean that it can access such items. Each Keychain items has a dictionary of attributes that are unique to that item. These are defined by you, the developer, and Firebase has no idea what those attributes are. It is only aware of the Keychain items that it creates.

I'm happy to point you to code in the Firebase SDK that accesses the keychain. Everything is [here](https://github.com/firebase/firebase-ios-sdk).

> If we get an awkward reviewer which sometimes happens, we still have no reason to use the keychain. Our answer can't be 'cause some SDK inside our app uses it' they won't accept that.

I understand. I think the justification can be more detailed as this is ultimately something that is trying to improve your app's user experience. [Firebase Installations](https://firebase.google.com/docs/projects/manage-installations) provides a table that provides a justification for why the SDK is used for each product. For instance, if you are using Firebase Messaging, it uses Installations to target devices for message delivery. The keychain is used to **securely** store the ID used to target that particular device.

--- 

Apologies if you are still not convinced. The fix in Firebase 9.6.0 was intended to quickly unblock Firebase developers targeting macOS apps. I will have more info in the coming weeks regarding what Firebase SDKs are ok to move away from the Keychain.

**Comment by ollydixon** [comment]
@ncooke3 

Thanks for the reply.

Still not convinced; have many more questions and security pokes; but I won’t take anymore time.

Really it’s a shame Google can’t give us a simple messaging service without using Firebase (which was GCM on Android and APN on Apple). Forcing developers to go though Firebase to increase sales; seems antitrust. Us developers always get screwed by this mobile duopoly 🤪

For us the keychain issue is still a deal breaker and a risk not worth taking. That keychain code could change at anytime exposing users sensitive data.

We decided to go with our own solution on MacOS 😎

Thanks for your help.

**Comment by GroovinChip** [comment]
@ncooke3 it seems like `package:cloud_firestore` is still using version `9.5.0` of the SDK. When can we expect to see an update that uses `9.6.0`?

**Comment by darshankawar** [comment]
Check this PR : https://github.com/firebase/flutterfire/pull/9531

**Comment by GroovinChip** [comment]
@darshankawar that's great, but `firebase_core` needs to be published to pub with `9.6.0` because `cloud_firestore` depends on it from pub, so depending on `cloud_firestore` from git and running `pod install` still brings in the `9.5.0` sdk. Really it would just be better if both packages were updated on pub. When can we expect this to happen?
