### ISSUE TITLE
🐛 [firebase_storage: ^10.3.1] Lexical or Preprocessor Issue (Xcode): 'FirebaseStorage/FIRStorageTypedefs.h' file not found

### ISSUE THREAD

**Issue by arnoorani** [firebase/flutterfire#9270]
'FirebaseStorage/FIRStorageTypedefs.h' file
not found
/Users/Desktop/Apps/Flutter_Dev/flutter2/flutter2_8/flutter/.pub-cac
he/hosted/pub.dartlang.org/firebase_storage-10.3.4/ios/Classes/FLTFirebaseStoragePl
ugin.m:6:8

suddenly started to get this error yesterday, is anyone else have this issue? 
Flutter 2.10.4

**Comment by FarhanAli-98** [comment]
I have also found this issue since two days ago .
When you try to run app on iOS simulator then issue is create.

**Comment by darshankawar** [comment]
@arnoorani 
I tried the `firebase_storage` plugin example using latest master and ran on iOS simulator which compiled and built without any issues:

![Screenshot 2022-08-01 at 12 55 14 PM](https://user-images.githubusercontent.com/67046386/182095951-7b0dd134-b9a1-4872-a1ee-843cbcd9629a.png)


![Screenshot 2022-08-01 at 12 55 30 PM](https://user-images.githubusercontent.com/67046386/182095987-bf19d4ba-5319-48b2-a0ed-bd51dfad9884.png)

I see that you are on older version of framework (Flutter 2.10.4), I recommend you to upgrade to latest stable (3.0.5), do a `flutter pub cache repair`, `flutter clean`, make sure all plugins you are using are on latest versions and try again.

**Comment by arnoorani** [comment]
@darshankawar were able to build an archive?

**Comment by darshankawar** [comment]
@arnoorani 
Yes. See below:

```
dhs@Dhss-MacBook-Pro firebase_storage_example % flutter build ipa
Running "flutter pub get" in firebase_storage_example...         1,661ms
 
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Archiving com.nevercode.triage...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running pod install...                                              3.3s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        15.2s
Xcode archive done.                                         113.1s
Built /Users/dhs/Documents/NCFlutter/triage-examples/flutterfire_examples/firebase_storage_example/build/ios/archive/Runner.xcarchive.
Building App Store IPA...                                          73.3s
Built IPA to /Users/dhs/Documents/NCFlutter/triage-examples/flutterfire_examples/firebase_storage_example/build/ios/ipa.
To upload to the App Store either:
    1. Drag and drop the "build/ios/ipa/*.ipa" bundle into the Apple Transport macOS app https://apps.apple.com/us/app/transporter/id1450874784
    2. Run "xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey your_api_key --apiIssuer your_issuer_id".
       See "man altool" for details about how to authenticate with the App Store Connect API key.
dhs@Dhss-MacBook-Pro firebase_storage_example % 

```

**Comment by arnoorani** [comment]
looks like the issue is resolved Thanks @darshankawar

**Comment by AresVampire** [comment]
This problem still happens with firebase_storage 10.3.5

firebase_storage-10.3.5/ios/Classes/FLTFirebaseStoragePlugin.m:7:9: note: did not find header 'FIRStorageTypedefs.h' in framework 'FirebaseStorage' (loaded from '/Volumes/Works/Work/Flutter/itsCoastal/palgo/build/ios/Debug-iphonesimulator/FirebaseStorage')

I am using Flutter 3.0.5

**Comment by arnoorani** [comment]
> This problem still happens with firebase_storage 10.3.5
> 
> firebase_storage-10.3.5/ios/Classes/FLTFirebaseStoragePlugin.m:7:9: note: did not find header 'FIRStorageTypedefs.h' in framework 'FirebaseStorage' (loaded from '/Volumes/Works/Work/Flutter/itsCoastal/palgo/build/ios/Debug-iphonesimulator/FirebaseStorage')
> 
> I am using Flutter 3.0.5

the issue is with the Firebase library versions, try upgrading them and make sure all of them use the same version of firebase_core.
