### ISSUE TITLE
🐛 [Firestore] Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds

### ISSUE THREAD

**Issue by noobcoder95** [firebase/flutterfire#9387]
## Bug report

**Describe the bug**
my app is using google_sign_in package to login then after login it will have to access firestore document.
when using android emulator api 33 and some real devices like oppo a 57 after login with google_sign_in nothing happen and then after few minutes waiting and cannot continue the login process, the console will produce something like this:

<details>
<summary> error log </summary>

```

W/MessengerIpcClient( 5850): Received response for unknown request: 1
D/TrafficStats( 5850): tagSocket(122) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5850): tagSocket(6) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5850): tagSocket(6) with statsTag=0xffffffff, statsUid=-1
W/System  ( 5850): Ignoring header X-Firebase-Locale because its value was null.
D/FirebaseAuth( 5850): Notifying id token listeners about user ( SDrPaL2xLVcFkwfhWK8UqeLXujw1 ).
D/FirebaseAuth( 5850): Notifying auth state listeners about user ( SDrPaL2xLVcFkwfhWK8UqeLXujw1 ).
D/EGL_emulation( 5850): app_time_stats: avg=124526.28ms min=7373.22ms max=241679.36ms count=2
W/DynamiteModule( 5850): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 5850): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 5850): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
D/nativeloader( 5850): classloader namespace configured for unbundled product apk. library_path=/product/priv-app/PrebuiltGmsCore/lib/x86_64:/product/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86_64:/product/lib64:/system/product/lib64
V/NativeCrypto( 5850): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 295 native methods...
W/nikindo.teknika( 5850): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (unsupported, reflection, allowed)
I/ProviderInstaller( 5850): Installed default security provider GmsCore_OpenSSL
D/TrafficStats( 5850): tagSocket(161) with statsTag=0xffffffff, statsUid=-1
W/Firestore( 5850): (24.2.2) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore( 5850): 
W/Firestore( 5850): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
E/flutter ( 5850): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
E/flutter ( 5850): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 5850): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 5850): <asynchronous suspension>
E/flutter ( 5850): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
E/flutter ( 5850): <asynchronous suspension>
E/flutter ( 5850): #3      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:68:42)
E/flutter ( 5850): <asynchronous suspension>
E/flutter ( 5850): #4      _JsonDocumentReference.get (package:cloud_firestore/src/document_reference.dart:146:7)
E/flutter ( 5850): <asynchronous suspension>
E/flutter ( 5850): 
W/Firestore( 5850): (24.2.2) [WatchStream]: (8bf792d) Stream closed with status: Status{code=UNAVAILABLE, description=Channel shutdownNow invoked, cause=null}.
W/DynamiteModule( 5850): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 5850): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 5850): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
D/TrafficStats( 5850): tagSocket(150) with statsTag=0xffffffff, statsUid=-1
W/DynamiteModule( 5850): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 5850): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 5850): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.

```

</details>

and for additional information, i have good internet speed, no firewall, no adblock or something that will block the firebase connection.

this bug is also happened few months ago but it fixed then until yesterday this bug is appear again.

### Steps to reproduce

Just make a simple app that using google_sign_in to access firestore database and run it in android emulator api 33

### Expected behavior

When it's normal, the app will just login fine and then it will access firestore database immediately without have to wait

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Arch Linux 5.19.2-arch1-1, locale en_US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
teknika 1.0.0+1

dependencies:
- android_id 0.0.7 [flutter]
- carousel_slider 4.1.1 [flutter]
- cloud_firestore 3.4.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.5
- device_info_plus 4.1.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- firebase_auth 3.6.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.21.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.3.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_local_notifications 9.8.0+1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_rating_bar 4.0.1 [flutter]
- font_awesome_flutter 10.1.0 [flutter]
- geolocator 9.0.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_fonts 3.0.1 [flutter http path_provider crypto]
- google_maps_flutter 2.1.12 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface]
- google_maps_place_picker_mb 2.0.0-mb.22 [flutter geolocator google_api_headers google_maps_flutter google_maps_webservice http location provider tuple uuid]
- google_sign_in 5.4.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- image_cropper 3.0.0 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- onesignal_flutter 3.4.1 [flutter]
- permission_handler 10.0.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- provider 6.0.3 [collection flutter nested]
- share_plus 4.0.10+1 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- smooth_page_indicator 1.0.0+2 [flutter]
- sn_progress_dialog 1.0.8 [flutter]
- sortedmap 0.5.1 [quiver]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 3.0.4 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- change_app_package_name 1.1.0
- dependency_validator 3.2.2 [args build_config checked_yaml glob io json_annotation logging package_config path pub_semver pubspec_parse yaml]
- flutter_launcher_icons 0.10.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_native_splash 2.2.7 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- archive 3.3.1 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build_config 1.1.0 [checked_yaml json_annotation path pubspec_parse yaml]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.7.2 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.5 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- dbus 0.7.7 [args ffi meta xml]
- device_info_plus_linux 3.0.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 3.0.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 3.0.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 4.0.0 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.3.0 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.5.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.2.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.14 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.4 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- geolocator_android 4.1.0 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- glob 2.1.0 [async collection file path string_scanner]
- google_api_headers 1.3.0 [flutter package_info_plus]
- google_maps_flutter_android 2.1.10 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.1.11 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.2.2 [collection flutter plugin_platform_interface stream_transform]
- google_maps_webservice 0.0.20-nullsafety.5 [http meta json_annotation]
- google_sign_in_android 6.0.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- image_cropper_for_web 1.0.2 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 3.0.2 [flutter plugin_platform_interface http]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- lint 1.10.0
- location 4.4.0 [flutter location_platform_interface location_web]
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus 1.4.3+1 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 2.0.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.19 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.2 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.0.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.1.0 [matcher]
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.1 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- webview_flutter_android 2.9.5 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.2 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.9.3 [flutter path webview_flutter_platform_interface]
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

```

</details>

---

**Comment by noobcoder95** [comment]
i'm trying run my app in another computer using android emulator and i get this in console debug:
W/Firestore( 9355): (24.2.2) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore( 9355): 
W/Firestore( 9355): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
W/Firestore( 9355): (24.2.2) [WatchStream]: (bb44886) Stream closed with status: Status{code=UNAVAILABLE, description=Channel shutdownNow invoked, cause=null}.
W/DynamiteModule( 9355): Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
I/DynamiteModule( 9355): Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
W/ProviderInstaller( 9355): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
E/flutter ( 9355): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
E/flutter ( 9355): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 9355): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 9355): <asynchronous suspension>
E/flutter ( 9355): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
E/flutter ( 9355): <asynchronous suspension>
E/flutter ( 9355): #3      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:68:42)
E/flutter ( 9355): <asynchronous suspension>
E/flutter ( 9355): #4      _JsonDocumentReference.get (package:cloud_firestore/src/document_reference.dart:146:7)
E/flutter ( 9355): <asynchronous suspension>
E/flutter ( 9355):

**Comment by noobcoder95** [comment]
I just run my app in iOS simulator using the latest release of Firestore sdk from this repo https://github.com/invertase/firestore-ios-sdk-frameworks.git and everything is fine.
Seems like this bug is only happen in android

**Comment by darshankawar** [comment]
@noobcoder95 
For `OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds`, please follow-up in https://github.com/firebase/flutterfire/discussions/5546 and check if any of the underlying comments help.

For `Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.`, please follow-up in https://github.com/firebase/flutterfire/discussions/5708 and check if any of the underlying comments help.

You also mentioned that you tried this on `android emulator api 33` which is Android 13 OS. Can you try it on lesser Android OS version and see if you still get same error / behavior or not ?

**Comment by noobcoder95** [comment]
@darshankawar after updating the package this bug is fix again. I don't really sure but I think the bug was from firebase_auth package

**Comment by darshankawar** [comment]
Good to know the issue is resolved at your end. Closing this based on comment above.

**Comment by noobcoder95** [comment]
@darshankawar hai there, it seems like this bug is reappear again, now i can't login with firebase, again and again. the log is still the same that I provided a week ago. I don't know what is wrong with firebase, because I don't do anything relate with firebase package but still this bug is reappear again. this so bad because its prevent me to continue my development

**Comment by noobcoder95** [comment]
please re open this issue and only close when it really solved

**Comment by Odalislnunez** [comment]
Hi! I have the same issue, and I've been involved on this since a month ago, I was working in a Mcincloud to test the code while I fix the error on my PC, but I lose the communication with the remote once and now I need to solve it here. I'm doing a master and I have to finish my final project for the next week. My application is an android kotlin one. I have already uninstalled and installed again the java, android studio, I make exceptions on the windows defender and still not working. I run the app in my friend's windows 11 computer and it works, but on mine is not, and I have the same. I check the internet conection in the emulator and my computer and it seems to be good. Can somebody help me with this, pleasee....

**Comment by darshankawar** [comment]
@noobcoder95 
If you are sure that the issue is with `firebase_auth` plugin, then we would need a complete reproducible code sample that triggers the error you are facing.

If not, then, as mentioned earlier, please follow-up in https://github.com/firebase/flutterfire/issues/9387#issuecomment-1221987070

**Comment by fleckdalm** [comment]
I have the very same issue. Any solution found?

**Comment by lucasnpc** [comment]
Hello Guys, I'm having the same issue :(

**Comment by mirek11s** [comment]
Same issue here

**Comment by CarlosZelayaTec** [comment]
I'm using react  native expo and am running an emulator to android, i have the same issue...

**Comment by darshankawar** [comment]
Everyone in thread facing the issue as titled, please follow-up in issues links mentioned in https://github.com/firebase/flutterfire/issues/9387#issuecomment-1221987070

If anybody has exact steps to replicate and narrow down the issue, please provide minimal code sample so that we can address it properly https://github.com/firebase/flutterfire/issues/9387#issuecomment-1236905310

**Comment by jmarrr** [comment]
I am getting this issue too with flutter

**Comment by vijendrasaini** [comment]
Facing the same issue. Please fix this issue.

**Comment by jmarrr** [comment]
This works fine if I use my physical device and different emulator like bluestacks. Might be related to android studio emulator

**Comment by Odalislnunez** [comment]
I used the same emulator in a Mcincloud, and it works fine. So I’m not pretty sure it can be that.

**Comment by fleckdalm** [comment]
Everything works fine on a real device but I keep getting this issue using the Android emulator. Any fix in sight?

**Comment by zubeirtech** [comment]
Facing same issue

**Comment by darshankawar** [comment]
As mentioned earlier, https://github.com/firebase/flutterfire/issues/9387#issuecomment-1251846509, please open new issue with all requested details in the issue template so that we can take a look at it.

This is a closed issue, so commenting on it with `facing same issue` or asking for updates here on resolution may not be answered.

**Comment by zubeirom** [comment]
Opened an issue: https://github.com/firebase/flutterfire/issues/9607

**Comment by yakitama5** [comment]
This can be handled by temporarily lowering the version of the Android emulator.
I am dealing with this by lowering the version to `31.2.10`.
https://stackoverflow.com/a/73584389/17550420
