### ISSUE TITLE
🐛 [firebase_storage] An unknown error occurred while calling method Reference#getDownloadURL when using Storage Emulator

### ISSUE THREAD

**Issue by rignaneseleo** [firebase/flutterfire#9787]
## Bug report

After updating the firebase libraries (check below the old and new versions), I get this error on iOS (both physical and simulator): 
```
FLTFirebaseStorage: An unknown error occurred while calling method Reference#getDownloadURL
2022-10-25 10:37:57.073419+0200 Runner[95060:20882028] flutter: error: Upload error: [firebase_storage/unknown] An unknown error occurred, please check the server response.
2022-10-25 10:37:57.075673+0200 Runner[95060:20882028] flutter: URL:null
```

I have updated my firebase libraries from 
```
  firebase_core: 1.24.0
  firebase_auth: 3.11.2
  firebase_storage: 10.3.11
  firebase_messaging: 13.1.0
  cloud_firestore: 3.5.1
```
to 
```
  firebase_core: 2.1.0
  firebase_auth: 4.0.2
  firebase_storage: 11.0.2
  firebase_messaging: 14.0.2
  cloud_firestore: 4.0.2
```

### Steps to reproduce

1. Execute  `fileRef.putFile()`
2. Check if the state of the upload is successful
3. Run `fileRef.getDownloadURL()`

### Expected behavior

The URL of the file should be returned like it did using the old firebase libraries.

### Sample code

This is the code I'm using:

```dart
 Reference storageRef = FirebaseStorage.instance.ref();

  if (intoUserArea) {
    var user = await PhoneAuthService.getUser();
    if (user == null) return null;
    storageRef = storageRef
        .child("authusers")
        //.child(globals.shareId.toString())
        .child(user.uid)
        .child(cloudFolder);
  } else
    storageRef = storageRef
        .child("shared")
        .child(globals.shareId.toString())
        .child(cloudFolder);

 var fileRef = storageRef.child(customFilename);

  try {
    await fileRef.putFile(
      File(filePath),
      SettableMetadata(
          contentType: mime(customFilename.toLowerCase()),
          customMetadata: {
            "deviceUUID": await getUUID(),
            "version": globals.printVersion(),
            "datetimeSinceEpoch":
                DateTime.now().toUtc().millisecondsSinceEpoch.toString()
          }),
    );

    final String url = (await fileRef.getDownloadURL());
    print('File uploaded on FirebaseStorage: $url');
    return url;
  } catch (e) {
    lError("Upload error: $e"); // FirebaseException
    return null;
  }
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.2
Flutter SDK 3.3.4
my_family 2.0.1+201

dependencies:
- after_layout 1.1.0 [flutter]
- animate_do 2.0.0 [flutter]
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- cloud_firestore 4.0.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- connectivity 3.0.6 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- contacts_service 0.6.3 [flutter collection quiver]
- device_info_plus 4.1.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- dio 4.0.4 [http_parser path]
- draggable_scrollbar 0.1.0 [flutter]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- file_picker 5.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_auth 4.0.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.0.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 11.0.2 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_custom_tabs 1.0.4 [flutter flutter_custom_tabs_platform_interface flutter_custom_tabs_web meta]
- flutter_fab_dialer 0.1.1 [flutter]
- flutter_image_compress 1.1.0 [flutter]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_mailer 2.0.1 [flutter]
- flutter_secure_storage 5.0.2 [meta flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows]
- flutter_slidable 0.6.0 [flutter]
- flutter_staggered_grid_view 0.6.1 [flutter]
- flutter_typeahead 4.1.0 [flutter flutter_keyboard_visibility]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- font_awesome_flutter 9.2.0 [flutter]
- gallery_saver 2.1.0 [flutter path_provider http path]
- get 4.6.1 [flutter]
- google_fonts 2.2.0 [flutter http path_provider crypto]
- google_sign_in 5.4.2 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- heic_to_jpg 0.1.3 [flutter]
- http 0.13.4 [async http_parser meta path]
- image_picker 0.8.4+5 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- json_annotation 4.4.0 [meta]
- media_gallery 0.1.3 [flutter]
- mime_type 1.0.0
- package_info 2.0.2 [flutter]
- page_indicator 0.4.1 [flutter]
- page_transition 2.0.5 [flutter]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 10.0.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- photo_manager 2.4.0 [flutter]
- photo_view 0.13.0 [flutter]
- printing 5.9.3 [ffi flutter flutter_web_plugins http image js meta pdf plugin_platform_interface]
- progress_dialog 1.2.4 [flutter]
- pull_to_refresh 2.0.0 [flutter]
- receive_sharing_intent 1.4.5 [flutter]
- reorderables 0.4.1 [flutter]
- scoped_model 1.1.0 [flutter]
- screenshot 1.2.3 [flutter]
- scrollable_positioned_list 0.1.7 [flutter meta]
- share_extend 2.0.0 [meta flutter]
- share_plus 3.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.12 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sqflite 2.0.2 [flutter sqflite_common path]
- synchronized 3.0.0
- table_calendar 3.0.7 [flutter intl simple_gesture_detector]
- url_launcher 6.0.18 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_compress 3.1.1 [flutter]
- video_thumbnail 0.5.2 [flutter]

dev dependencies:
- change_app_package_name 1.0.0
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

dependency overrides:
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]

transitive dependencies:
- _flutterfire_internals 1.0.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.1 [crypto path]
- args 2.3.1
- asn1lib 1.1.0
- async 2.9.0 [collection meta]
- barcode 2.2.1 [meta qr]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.8.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.0.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- connectivity_for_web 0.4.0+1 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.1+2 [flutter connectivity_platform_interface]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.0.2 [typed_data]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- cupertino_icons 1.0.5
- device_info_plus_linux 3.0.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 3.0.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 3.0.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 4.1.0 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.10.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.0.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_web 2.0.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.2.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.3 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.21 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.12 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_custom_tabs_platform_interface 1.0.1 [flutter plugin_platform_interface meta]
- flutter_custom_tabs_web 1.0.0 [flutter flutter_web_plugins flutter_custom_tabs_platform_interface meta url_launcher_web url_launcher_platform_interface]
- flutter_keyboard_visibility 5.3.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_secure_storage_linux 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_sign_in_android 6.1.0 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- octo_image 1.0.2 [flutter flutter_blurhash]
- path 1.8.2
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.17 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- pdf 3.8.2 [archive barcode crypto image meta path_parsing vector_math xml]
- pedantic 1.11.1
- permission_handler_android 10.0.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pointycastle 3.6.1 [collection convert js]
- process 4.2.4 [file path platform]
- provider 5.0.0 [collection flutter nested]
- qr 3.0.1 [meta]
- quiver 3.1.0 [matcher]
- rxdart 0.27.5
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.1.0 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.1.0 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- simple_gesture_detector 0.2.0 [flutter]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 2.0.3 [flutter]
- url_launcher_macos 2.0.3 [flutter]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- video_player 2.4.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.3.8 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.3 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by danagbemava-nc** [comment]
Hi @rignaneseleo, is this issue only on iOS, or are you also experiencing this issue on android? 

If this is also on android, can you share the logs? 

I tried the `firebase_storage` example code, which calls the methods you've referenced above and everything works as expected. 

Can you share a complete minimal reproducible code sample as well?

**Comment by JavierPerezLavadie** [comment]
Hi, Maybe it's the same if you use the Firebase emulator

https://github.com/firebase/flutterfire/issues/9791

**Comment by JavierPerezLavadie** [comment]
it can help I think it's known bugs of the last version I should have waited before updating

https://github.com/firebase/firebase-ios-sdk/issues/10374

**Comment by rignaneseleo** [comment]
> 

It's ONLY on iOS. The issue is the same reported by Javier.

**Comment by danagbemava-nc** [comment]
I can reproduce the issue only when using the storage emulator. 

```
FLTFirebaseStorage: An unknown error occurred while calling method Reference#getDownloadURL
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_storage/unknown] An unknown error occurred, please check the server response.
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:499
<asynchronous suspension>
#3      MethodChannelReference.getDownloadURL
package:firebase_storage_platform_interface/…/method_channel/method_channel_reference.dart:45
<asynchronous suspension>
#4      _TaskManager._downloadLink
package:triage/main.dart:162
<asynchronous suspension>
```

**Comment by russellwheatley** [comment]
This has been fixed on the iOS SDK and will be part of the next release I believe: https://github.com/firebase/firebase-ios-sdk/pull/10370

**Comment by rignaneseleo** [comment]
I'm now using the updated libraries:
```
  firebase_core: 2.1.1
  firebase_auth: 4.1.0
  firebase_storage: 11.0.3
  firebase_messaging: 14.0.3
  cloud_firestore: 4.0.3
```

But the problem still occurs (only on iOS):
```
FLTFirebaseStorage: An unknown error occurred while calling method Reference#getDownloadURL
flutter: error: Upload error: [firebase_storage/unknown] An unknown error occurred, please check the server response.
```

**Comment by jslattery26** [comment]
Same here. on my real device, iOS only. I realized that while having metadata

```dart
final metadata = SettableMetadata(
      owner: uid,
      contentType: file.mimeType,
    );
uploadTask = ref.putFile(File(file.path), metadata);
```
I get the error.. then after removing it.. 
```dart
uploadTask = ref.putFile(File(file.path));
```
It works. can anyone confirm?

**Comment by duduBaiao** [comment]
This is happening to me as well, only on iOS.
I'm running it on a real device:

```
[+20953 ms] FLTFirebaseStorage: An unknown error occurred while calling method Reference#getDownloadURL
[        ] flutter: SEVERE: [firebase_storage/unknown] An unknown error occurred, please check the server response.
[        ] flutter: [firebase_storage/unknown] An unknown error occurred, please check the server response.
[        ] flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
[        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
[        ] <asynchronous suspension>
[        ] #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
[        ] <asynchronous suspension>
[        ] #3      MethodChannelReference.getDownloadURL (package:firebase_storage_platform_interface/src/method_channel/method_channel_reference.dart:45:36)
[        ] <asynchronous suspension>
[        ] #4      RemoteStorageImpl._uploadFile.<anonymous closure> (package:storage/remote_storage.dart:76:31)
```

**Comment by russellwheatley** [comment]
The fix has been released in Firebase iOS SDK `10.1.0`. I've created a PR to update.

**Comment by rignaneseleo** [comment]
Thanks @russellwheatley 
Any way I can use this fix before the merge?

**Comment by cyberpwnn** [comment]
Is this merged yet?

**Comment by rignaneseleo** [comment]
> Is this merged yet?

I think so! It's in release

**Comment by AlmogRnD** [comment]
Has this fix been released?
